"""added columns to agent table

Revision ID: 00898b55ef80
Revises: 8949ec845f35
Create Date: 2026-02-03 12:10:14.377788

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '00898b55ef80'
down_revision = '8949ec845f35'
branch_labels = None
depends_on = None

agenttype_enum = sa.Enum(
    "bot",
    "human",
    name="agenttype"
)


def upgrade() -> None:
    agenttype_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, default={}))
    op.add_column('agents', sa.Column('status', sa.String(), nullable=True, default='active'))
    op.add_column('agents', sa.Column('agent_type', sa.Enum('INBOUND', 'OUTBOUND', 'CHATBOT', name='agenttype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'agent_type')
    op.drop_column('agents', 'status')
    op.drop_column('agents', 'meta_data')
    agenttype_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
