"""Added created_by key in channel

Revision ID: 1487086f6ba8
Revises: e268c5acbe84
Create Date: 2026-02-25 16:49:32.281404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1487086f6ba8'
down_revision = 'e268c5acbe84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('created_by', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'created_by')
    # ### end Alembic commands ###
