"""add model_id to voices table

Revision ID: 5effdb345c65
Revises: d1a2b3c4e5f6
Create Date: 2026-03-03 13:06:29.278334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5effdb345c65'
down_revision = 'd1a2b3c4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voices', sa.Column('model_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'voices', 'models', ['model_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voices', type_='foreignkey')
    op.drop_column('voices', 'model_id')
    # ### end Alembic commands ###
