"""Made changes in channel table and created new relationship table agent and channels

Revision ID: e268c5acbe84
Revises: 13104cf476f7
Create Date: 2026-02-25 15:32:45.454035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e268c5acbe84'
down_revision = '13104cf476f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_channels',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'channel_id', name='agent_channel_unique'),
    sa.UniqueConstraint('uuid')
    )
    op.add_column('agent_phone_numbers', sa.Column('channel_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'agent_phone_numbers', 'channels', ['channel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agent_phone_numbers', type_='foreignkey')
    op.drop_column('agent_phone_numbers', 'channel_id')
    op.drop_table('agent_channels')
    # ### end Alembic commands ###
