"""added agent tables

Revision ID: ebf78bf156a0
Revises: a16d6426e42f
Create Date: 2026-01-30 15:35:14.048477

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ebf78bf156a0'
down_revision = 'a16d6426e42f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_calls', sa.Integer(), nullable=True),
    sa.Column('total_minutes', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('average_rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='agent_name_unique'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('agent_configs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('agent_id', sa.BigInteger(), nullable=False),
    sa.Column('llm_service_id', sa.BigInteger(), nullable=True),
    sa.Column('tts_service_id', sa.BigInteger(), nullable=True),
    sa.Column('stt_service_id', sa.BigInteger(), nullable=True),
    sa.Column('first_message', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('end_call_message', sa.Text(), nullable=True),
    sa.Column('voicemail_message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('llm_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('tts_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('stt_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('agent_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['llm_service_id'], ['service_providers.id'], ),
    sa.ForeignKeyConstraint(['stt_service_id'], ['service_providers.id'], ),
    sa.ForeignKeyConstraint(['tts_service_id'], ['service_providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', name='agent_config_agent_id_unique'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('agent_phone_numbers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('agent_id', sa.BigInteger(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('phone_number_sid', sa.String(), nullable=False),
    sa.Column('phone_number_auth_token', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('number_type', sa.String(), nullable=True),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'phone_number', name='agent_phone_numbers_agent_phone_unique'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('uuid')
    )
    op.alter_column('organization_invites', 'uuid',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('users', 'uuid',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'uuid',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('organization_invites', 'uuid',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.drop_table('agent_phone_numbers')
    op.drop_table('agent_configs')
    op.drop_table('agents')
    # ### end Alembic commands ###
