"""added columns to model table

Revision ID: f6b23d0ef6b4
Revises: 00898b55ef80
Create Date: 2026-02-03 13:57:58.183844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6b23d0ef6b4'
down_revision = '00898b55ef80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('api_key_id', sa.BigInteger(), nullable=True))
    op.add_column('models', sa.Column('status', sa.String(), nullable=True))
    op.add_column('models', sa.Column('service_type', sa.String(), nullable=True))
    op.create_foreign_key(None, 'models', 'api_keys', ['api_key_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'models', type_='foreignkey')
    op.drop_column('models', 'service_type')
    op.drop_column('models', 'status')
    op.drop_column('models', 'api_key_id')
    # ### end Alembic commands ###
