"""added language_list for voices

Revision ID: 00950b136fcb
Revises: 382f48507b4b
Create Date: 2026-03-27 16:34:07.318510

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '00950b136fcb'
down_revision = '382f48507b4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voices', sa.Column('language_list', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voices', 'language_list')
    # ### end Alembic commands ###
