"""add is_template and name to agent_configs

Revision ID: 1b30e7c3d05f
Revises: c4e1f7a9b3d2
Create Date: 2026-07-09 10:24:00.140019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b30e7c3d05f'
down_revision = 'd9e4b8c1a2f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Only the two new agent_configs columns — unrelated autogenerated drift
    # (indexes/FKs on other tables) was intentionally removed.
    op.add_column(
        'agent_configs',
        sa.Column('is_template', sa.Boolean(), server_default='false', nullable=False),
    )
    op.add_column('agent_configs', sa.Column('name', sa.String(length=200), nullable=True))


def downgrade() -> None:
    op.drop_column('agent_configs', 'name')
    op.drop_column('agent_configs', 'is_template')
