"""added model_id for voices

Revision ID: 382f48507b4b
Revises: 19cebc5ddf80
Create Date: 2026-03-27 16:00:19.282605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382f48507b4b'
down_revision = '19cebc5ddf80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('voices', sa.Column('model_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'voices', 'models', ['model_id'], ['id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voices', type_='foreignkey')
    op.drop_column('voices', 'model_id')
    # ### end Alembic commands ###
