"""Added change in auth-type column

Revision ID: 42c30a58e528
Revises: a13bb54c4b8f
Create Date: 2026-05-07 13:14:21.468448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42c30a58e528'
down_revision = 'a13bb54c4b8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.alter_column('tools', 'auth_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tools', 'auth_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
