"""Added mcp and tool idfor tool executions

Revision ID: 4e4fc977b458
Revises: 62ed186f77e5
Create Date: 2026-06-23 17:49:19.418992

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4e4fc977b458'
down_revision = '62ed186f77e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool_executions', sa.Column('tool_id', sa.UUID(), nullable=True))
    op.add_column('tool_executions', sa.Column('mcp_server_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_tool_executions_mcp_server_id'), 'tool_executions', ['mcp_server_id'], unique=False)
    op.create_index(op.f('ix_tool_executions_tool_id'), 'tool_executions', ['tool_id'], unique=False)
    op.create_foreign_key(None, 'tool_executions', 'tools', ['tool_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tool_executions', 'mcp_servers', ['mcp_server_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tool_executions', type_='foreignkey')
    op.drop_constraint(None, 'tool_executions', type_='foreignkey')
    op.drop_index(op.f('ix_tool_executions_tool_id'), table_name='tool_executions')
    op.drop_index(op.f('ix_tool_executions_mcp_server_id'), table_name='tool_executions')
    op.drop_column('tool_executions', 'mcp_server_id')
    op.drop_column('tool_executions', 'tool_id')
    # ### end Alembic commands ###
