"""add sip_trunks

Revision ID: 550f0ed26622
Revises: b71c3e5a9f42
Create Date: 2026-08-24 10:14:44.176391

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '550f0ed26622'
down_revision = 'b71c3e5a9f42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sip_trunks',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('carrier', sa.String(length=50), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('gateways', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('inbound_enabled', sa.Boolean(), nullable=False),
    sa.Column('outbound_enabled', sa.Boolean(), nullable=False),
    sa.Column('auth_mode', sa.String(length=20), nullable=False),
    sa.Column('auth_username', sa.String(length=128), nullable=True),
    sa.Column('encrypted_auth', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('register_enabled', sa.Boolean(), nullable=False),
    sa.Column('tech_prefix', sa.String(length=32), nullable=True),
    sa.Column('sip_diversion_header', sa.Boolean(), nullable=False),
    sa.Column('outbound_leading_plus_enabled', sa.Boolean(), nullable=False),
    sa.Column('number_e164_check_enabled', sa.Boolean(), nullable=False),
    sa.Column('transfer_enabled', sa.Boolean(), nullable=False),
    sa.Column('media_encryption', sa.String(length=20), nullable=False),
    sa.Column('carrier_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('status_detail', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', name='uq_sip_trunks_channel_id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_sip_trunks_org_name')
    )
    op.create_index('ix_sip_trunks_auth_username', 'sip_trunks', ['auth_username'], unique=False)
    op.create_index(op.f('ix_sip_trunks_organization_id'), 'sip_trunks', ['organization_id'], unique=False)
   
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sip_trunks_organization_id'), table_name='sip_trunks')
    op.drop_index('ix_sip_trunks_auth_username', table_name='sip_trunks')
    op.drop_table('sip_trunks')
    # ### end Alembic commands ###
