"""add node capacity columns

Revision ID: 5818d16712be
Revises: a425f95775d9
Create Date: 2026-07-06 19:39:07.580820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5818d16712be'
down_revision = 'a425f95775d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('total_vcpu', sa.Float(), nullable=True))
    op.add_column('nodes', sa.Column('total_ram_mb', sa.Integer(), nullable=True))
    op.add_column('nodes', sa.Column('vcpu_per_pod', sa.Float(), nullable=True))
    op.add_column('nodes', sa.Column('ram_per_pod_mb', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'ram_per_pod_mb')
    op.drop_column('nodes', 'vcpu_per_pod')
    op.drop_column('nodes', 'total_ram_mb')
    op.drop_column('nodes', 'total_vcpu')
    # ### end Alembic commands ###
