"""Added base_url to models

Revision ID: 667f05ffd49b
Revises: 56e0fb796b3e
Create Date: 2026-06-09 09:53:08.972846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '667f05ffd49b'
down_revision = '56e0fb796b3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('base_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'base_url')
    # ### end Alembic commands ###
