"""add agent_channels

Revision ID: 6696b9e0556b
Revises: 62ed186f77e5
Create Date: 2026-06-23 15:40:05.355489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6696b9e0556b'
down_revision = '62ed186f77e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'agent_channels',
        sa.Column('agent_id', sa.UUID(), nullable=False),
        sa.Column('channel_id', sa.UUID(), nullable=False),
        sa.Column('slug', sa.String(length=64), nullable=False),
        sa.Column('organization_id', sa.UUID(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('agent_id', 'channel_id', name='uq_agent_channels_agent_channel'),
        sa.UniqueConstraint('slug', name='uq_agent_channels_slug'),
    )
    op.create_index(op.f('ix_agent_channels_agent_id'), 'agent_channels', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_channels_channel_id'), 'agent_channels', ['channel_id'], unique=False)
    op.create_index(op.f('ix_agent_channels_organization_id'), 'agent_channels', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_channels_organization_id'), table_name='agent_channels')
    op.drop_index(op.f('ix_agent_channels_channel_id'), table_name='agent_channels')
    op.drop_index(op.f('ix_agent_channels_agent_id'), table_name='agent_channels')
    op.drop_table('agent_channels')
    # ### end Alembic commands ###
