"""add agent_configs turn_settings

Revision ID: 690c618340d6
Revises: e2f8a1c4b7d3
Create Date: 2026-09-07 18:51:24.318778

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '690c618340d6'
down_revision = 'e2f8a1c4b7d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_configs', sa.Column('turn_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_configs', 'turn_settings')
    # ### end Alembic commands ###
