"""add procrastinate_job_id, doc_type, ingestion_stats to knowledge_bases

Revision ID: 6bd88c8ee3dc
Revises: b2e9f47a1c30
Create Date: 2026-06-05 15:52:40.116022

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6bd88c8ee3dc'
down_revision = 'b2e9f47a1c30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_bases', sa.Column('procrastinate_job_id', sa.BigInteger(), nullable=True))
    op.add_column('knowledge_bases', sa.Column('doc_type', sa.String(length=32), nullable=True))
    op.add_column('knowledge_bases', sa.Column('ingestion_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_knowledge_bases_procrastinate_job_id'), 'knowledge_bases', ['procrastinate_job_id'], unique=False)
    op.create_foreign_key('fk_knowledge_bases_procrastinate_job_id', 'knowledge_bases', 'procrastinate_jobs', ['procrastinate_job_id'], ['id'], ondelete='SET NULL',)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_knowledge_bases_procrastinate_job_id', 'knowledge_bases', type_='foreignkey')
    op.drop_index(op.f('ix_knowledge_bases_procrastinate_job_id'), table_name='knowledge_bases')
    op.drop_column('knowledge_bases', 'ingestion_stats')
    op.drop_column('knowledge_bases', 'doc_type')
    op.drop_column('knowledge_bases', 'procrastinate_job_id')
    # ### end Alembic commands ###
