"""add pod live resource columns

Revision ID: 733a3ca12fdb
Revises: 5818d16712be
Create Date: 2026-07-07 16:39:53.401380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '733a3ca12fdb'
down_revision = '5818d16712be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pods', sa.Column('mem_used_mb', sa.Float(), nullable=True))
    op.add_column('pods', sa.Column('mem_limit_mb', sa.Float(), nullable=True))
    op.add_column('pods', sa.Column('cpu_used_cores', sa.Float(), nullable=True))
    op.add_column('pods', sa.Column('cpu_limit_cores', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pods', 'cpu_limit_cores')
    op.drop_column('pods', 'cpu_used_cores')
    op.drop_column('pods', 'mem_limit_mb')
    op.drop_column('pods', 'mem_used_mb')
    # ### end Alembic commands ###
