"""add uploads table and link to call_logs

Revision ID: 7a18e9b73090
Revises: 2190a0cc1ca8
Create Date: 2026-03-19 18:24:48.017211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a18e9b73090'
down_revision = '2190a0cc1ca8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploads',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('r2_object_key', sa.String(), nullable=False),
    sa.Column('agent_id', sa.BigInteger(), nullable=False),
    sa.Column('call_log_id', sa.BigInteger(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['call_log_id'], ['call_logs.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_uploads_agent_id'), 'uploads', ['agent_id'], unique=False)
    op.create_index(op.f('ix_uploads_call_log_id'), 'uploads', ['call_log_id'], unique=False)
    op.create_index(op.f('ix_uploads_organization_id'), 'uploads', ['organization_id'], unique=False)
    op.add_column('call_logs', sa.Column('upload_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_call_logs_upload_id'), 'call_logs', ['upload_id'], unique=False)
    op.create_foreign_key('fk_call_logs_upload_id', 'call_logs', 'uploads', ['upload_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_call_logs_upload_id', 'call_logs', type_='foreignkey')
    op.drop_index(op.f('ix_call_logs_upload_id'), table_name='call_logs')
    op.drop_column('call_logs', 'upload_id')
    op.drop_index(op.f('ix_uploads_organization_id'), table_name='uploads')
    op.drop_index(op.f('ix_uploads_call_log_id'), table_name='uploads')
    op.drop_index(op.f('ix_uploads_agent_id'), table_name='uploads')
    op.drop_table('uploads')
    # ### end Alembic commands ###
