"""added meta data schema for models

Revision ID: 9faf9806b065
Revises: 90a99bb1d5a1
Create Date: 2026-06-03 12:38:04.323494

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9faf9806b065'
down_revision = '90a99bb1d5a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_api_keys_one_default_per_org_type', table_name='api_keys')
    op.alter_column('invites', 'token',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('invites', 'invited_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('invites', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint('uq_invites_org_email', 'invites', type_='unique')
    op.drop_index('ix_document_chunks_embedding_hnsw', table_name='knowledge_base_chunks')
    op.drop_index('ix_document_chunks_organization_id', table_name='knowledge_base_chunks')
    op.create_index(op.f('ix_knowledge_base_chunks_organization_id'), 'knowledge_base_chunks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_members_user_id'), 'members', ['user_id'], unique=False)
    op.drop_column('members', 'created_at')
    op.drop_column('members', 'is_active')
    op.drop_column('members', 'deleted_at')
    op.drop_column('members', 'archived_at')
    op.drop_column('members', 'updated_at')
    op.add_column('models', sa.Column('meta_data_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_constraint('uq_organizations_slug', 'organizations', type_='unique')
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.create_unique_constraint('uq_organizations_slug', 'organizations', ['slug'])
    op.drop_column('models', 'meta_data_schema')
    op.add_column('members', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('members', sa.Column('archived_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('members', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('members', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('members', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_members_user_id'), table_name='members')
    op.drop_index(op.f('ix_knowledge_base_chunks_organization_id'), table_name='knowledge_base_chunks')
    op.create_index('ix_document_chunks_organization_id', 'knowledge_base_chunks', ['organization_id'], unique=False)
    op.create_index('ix_document_chunks_embedding_hnsw', 'knowledge_base_chunks', ['embedding'], unique=False)
    op.create_unique_constraint('uq_invites_org_email', 'invites', ['organization_id', 'email'])
    op.alter_column('invites', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('invites', 'invited_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('invites', 'token',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index('uq_api_keys_one_default_per_org_type', 'api_keys', ['organization_id', 'service_type'], unique=False)
    # ### end Alembic commands ###
