"""add nodes pods and call pod_id fk

Revision ID: a425f95775d9
Revises: f3a1c7e5d9b2
Create Date: 2026-07-06 18:33:56.241703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a425f95775d9'
down_revision = 'f3a1c7e5d9b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_environment'), 'nodes', ['environment'], unique=False)
    op.create_index(op.f('ix_nodes_name'), 'nodes', ['name'], unique=True)
    op.create_table('pods',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pods_environment'), 'pods', ['environment'], unique=False)
    op.create_index(op.f('ix_pods_name'), 'pods', ['name'], unique=True)
    op.create_index(op.f('ix_pods_node_id'), 'pods', ['node_id'], unique=False)
    op.add_column('calls', sa.Column('pod_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_calls_pod_id'), 'calls', ['pod_id'], unique=False)
    op.create_foreign_key('fk_calls_pod_id_pods', 'calls', 'pods', ['pod_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_calls_pod_id_pods', 'calls', type_='foreignkey')
    op.drop_index(op.f('ix_calls_pod_id'), table_name='calls')
    op.drop_column('calls', 'pod_id')
    op.drop_index(op.f('ix_pods_node_id'), table_name='pods')
    op.drop_index(op.f('ix_pods_name'), table_name='pods')
    op.drop_index(op.f('ix_pods_environment'), table_name='pods')
    op.drop_table('pods')
    op.drop_index(op.f('ix_nodes_name'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_environment'), table_name='nodes')
    op.drop_table('nodes')
    # ### end Alembic commands ###
