"""add call_logs table

Revision ID: ea87145a1dc0
Revises: ed86ce4db4f1
Create Date: 2026-03-19 10:49:17.771892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea87145a1dc0'
down_revision = 'ed86ce4db4f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_logs',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.BigInteger(), nullable=False),
    sa.Column('provider_call_id', sa.String(), nullable=True),
    sa.Column('transport_type', sa.String(), nullable=True),
    sa.Column('from_number', sa.String(), nullable=True),
    sa.Column('to_number', sa.String(), nullable=True),
    sa.Column('audio_file_path', sa.String(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.BigInteger(), nullable=False),
    sa.Column('ended_at', sa.BigInteger(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_call_logs_agent_id'), 'call_logs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_call_logs_organization_id'), 'call_logs', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_logs_organization_id'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_agent_id'), table_name='call_logs')
    op.drop_table('call_logs')
    # ### end Alembic commands ###
