"""Added meta_data for model

Revision ID: eaed98724a40
Revises: b7e1c0a2d9f3
Create Date: 2026-06-02 15:50:46.728257

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eaed98724a40'
down_revision = 'b7e1c0a2d9f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'meta_data')
