"""add channel_phone_numbers table

Revision ID: ed86ce4db4f1
Revises: 085456519e69
Create Date: 2026-03-18 18:34:03.828233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed86ce4db4f1'
down_revision = '085456519e69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_phone_numbers',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('phone_number_sid', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('number_type', sa.String(), nullable=True),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('friendly_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'channel_id', 'phone_number', name='channel_phone_number_org_unique'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_channel_phone_numbers_organization_id'), 'channel_phone_numbers', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_phone_numbers_organization_id'), table_name='channel_phone_numbers')
    op.drop_table('channel_phone_numbers')
    # ### end Alembic commands ###
