"""add mcp_servers and agent_mcp_servers tables

Revision ID: ff9ab48e9816
Revises: 6a6a40878188
Create Date: 2026-05-12 10:18:12.105479

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ff9ab48e9816'
down_revision = '6a6a40878188'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_servers',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('server_url', sa.String(), nullable=False),
    sa.Column('transport_type', sa.String(), nullable=False),
    sa.Column('auth_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_mcp_servers_organization_id'), 'mcp_servers', ['organization_id'], unique=False)
    op.create_table('agent_mcp_servers',
    sa.Column('agent_id', sa.BigInteger(), nullable=False),
    sa.Column('mcp_server_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mcp_server_id'], ['mcp_servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_mcp_servers_agent_id'), 'agent_mcp_servers', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_mcp_servers_mcp_server_id'), 'agent_mcp_servers', ['mcp_server_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_mcp_servers_mcp_server_id'), table_name='agent_mcp_servers')
    op.drop_index(op.f('ix_agent_mcp_servers_agent_id'), table_name='agent_mcp_servers')
    op.drop_table('agent_mcp_servers')
    op.drop_index(op.f('ix_mcp_servers_organization_id'), table_name='mcp_servers')
    op.drop_table('mcp_servers')
    # ### end Alembic commands ###
