export interface CountryCode {
  name: string;
  dialCode: string;
  iso2: string;
}

/**
 * Country codes sorted by dial code length (longest first) so that
 * prefix matching picks the most specific code.
 * E.g. +1‑868 (Trinidad) matches before the generic +1 (US).
 */
export const COUNTRY_CODES: CountryCode[] = [
  // ── Caribbean & NANP overlays (3-digit after +1) ────────────
  { name: 'Trinidad and Tobago', dialCode: '+1868', iso2: 'TT' },
  { name: 'Jamaica', dialCode: '+1876', iso2: 'JM' },
  { name: 'Barbados', dialCode: '+1246', iso2: 'BB' },
  { name: 'Bahamas', dialCode: '+1242', iso2: 'BS' },
  { name: 'Bermuda', dialCode: '+1441', iso2: 'BM' },
  { name: 'Dominican Republic', dialCode: '+1809', iso2: 'DO' },
  { name: 'Puerto Rico', dialCode: '+1787', iso2: 'PR' },
  { name: 'Virgin Islands (US)', dialCode: '+1340', iso2: 'VI' },

  // ── 4-digit dial codes ──────────────────────────────────────
  { name: 'Norfolk Island', dialCode: '+6723', iso2: 'NF' },

  // ── 3-digit dial codes ──────────────────────────────────────
  { name: 'Afghanistan', dialCode: '+93', iso2: 'AF' },
  { name: 'Albania', dialCode: '+355', iso2: 'AL' },
  { name: 'Algeria', dialCode: '+213', iso2: 'DZ' },
  { name: 'Angola', dialCode: '+244', iso2: 'AO' },
  { name: 'Argentina', dialCode: '+54', iso2: 'AR' },
  { name: 'Armenia', dialCode: '+374', iso2: 'AM' },
  { name: 'Australia', dialCode: '+61', iso2: 'AU' },
  { name: 'Austria', dialCode: '+43', iso2: 'AT' },
  { name: 'Azerbaijan', dialCode: '+994', iso2: 'AZ' },
  { name: 'Bahrain', dialCode: '+973', iso2: 'BH' },
  { name: 'Bangladesh', dialCode: '+880', iso2: 'BD' },
  { name: 'Belarus', dialCode: '+375', iso2: 'BY' },
  { name: 'Belgium', dialCode: '+32', iso2: 'BE' },
  { name: 'Belize', dialCode: '+501', iso2: 'BZ' },
  { name: 'Benin', dialCode: '+229', iso2: 'BJ' },
  { name: 'Bhutan', dialCode: '+975', iso2: 'BT' },
  { name: 'Bolivia', dialCode: '+591', iso2: 'BO' },
  { name: 'Bosnia and Herzegovina', dialCode: '+387', iso2: 'BA' },
  { name: 'Botswana', dialCode: '+267', iso2: 'BW' },
  { name: 'Brazil', dialCode: '+55', iso2: 'BR' },
  { name: 'Brunei', dialCode: '+673', iso2: 'BN' },
  { name: 'Bulgaria', dialCode: '+359', iso2: 'BG' },
  { name: 'Burkina Faso', dialCode: '+226', iso2: 'BF' },
  { name: 'Cambodia', dialCode: '+855', iso2: 'KH' },
  { name: 'Cameroon', dialCode: '+237', iso2: 'CM' },
  { name: 'Canada', dialCode: '+1', iso2: 'CA' },
  { name: 'Chile', dialCode: '+56', iso2: 'CL' },
  { name: 'China', dialCode: '+86', iso2: 'CN' },
  { name: 'Colombia', dialCode: '+57', iso2: 'CO' },
  { name: 'Congo (DRC)', dialCode: '+243', iso2: 'CD' },
  { name: 'Costa Rica', dialCode: '+506', iso2: 'CR' },
  { name: 'Croatia', dialCode: '+385', iso2: 'HR' },
  { name: 'Cuba', dialCode: '+53', iso2: 'CU' },
  { name: 'Cyprus', dialCode: '+357', iso2: 'CY' },
  { name: 'Czech Republic', dialCode: '+420', iso2: 'CZ' },
  { name: 'Denmark', dialCode: '+45', iso2: 'DK' },
  { name: 'Ecuador', dialCode: '+593', iso2: 'EC' },
  { name: 'Egypt', dialCode: '+20', iso2: 'EG' },
  { name: 'El Salvador', dialCode: '+503', iso2: 'SV' },
  { name: 'Estonia', dialCode: '+372', iso2: 'EE' },
  { name: 'Ethiopia', dialCode: '+251', iso2: 'ET' },
  { name: 'Finland', dialCode: '+358', iso2: 'FI' },
  { name: 'France', dialCode: '+33', iso2: 'FR' },
  { name: 'Georgia', dialCode: '+995', iso2: 'GE' },
  { name: 'Germany', dialCode: '+49', iso2: 'DE' },
  { name: 'Ghana', dialCode: '+233', iso2: 'GH' },
  { name: 'Greece', dialCode: '+30', iso2: 'GR' },
  { name: 'Guatemala', dialCode: '+502', iso2: 'GT' },
  { name: 'Honduras', dialCode: '+504', iso2: 'HN' },
  { name: 'Hong Kong', dialCode: '+852', iso2: 'HK' },
  { name: 'Hungary', dialCode: '+36', iso2: 'HU' },
  { name: 'Iceland', dialCode: '+354', iso2: 'IS' },
  { name: 'India', dialCode: '+91', iso2: 'IN' },
  { name: 'Indonesia', dialCode: '+62', iso2: 'ID' },
  { name: 'Iran', dialCode: '+98', iso2: 'IR' },
  { name: 'Iraq', dialCode: '+964', iso2: 'IQ' },
  { name: 'Ireland', dialCode: '+353', iso2: 'IE' },
  { name: 'Israel', dialCode: '+972', iso2: 'IL' },
  { name: 'Italy', dialCode: '+39', iso2: 'IT' },
  { name: 'Ivory Coast', dialCode: '+225', iso2: 'CI' },
  { name: 'Japan', dialCode: '+81', iso2: 'JP' },
  { name: 'Jordan', dialCode: '+962', iso2: 'JO' },
  { name: 'Kazakhstan', dialCode: '+7', iso2: 'KZ' },
  { name: 'Kenya', dialCode: '+254', iso2: 'KE' },
  { name: 'Kuwait', dialCode: '+965', iso2: 'KW' },
  { name: 'Laos', dialCode: '+856', iso2: 'LA' },
  { name: 'Latvia', dialCode: '+371', iso2: 'LV' },
  { name: 'Lebanon', dialCode: '+961', iso2: 'LB' },
  { name: 'Libya', dialCode: '+218', iso2: 'LY' },
  { name: 'Lithuania', dialCode: '+370', iso2: 'LT' },
  { name: 'Luxembourg', dialCode: '+352', iso2: 'LU' },
  { name: 'Macau', dialCode: '+853', iso2: 'MO' },
  { name: 'Malaysia', dialCode: '+60', iso2: 'MY' },
  { name: 'Maldives', dialCode: '+960', iso2: 'MV' },
  { name: 'Mali', dialCode: '+223', iso2: 'ML' },
  { name: 'Malta', dialCode: '+356', iso2: 'MT' },
  { name: 'Mexico', dialCode: '+52', iso2: 'MX' },
  { name: 'Moldova', dialCode: '+373', iso2: 'MD' },
  { name: 'Mongolia', dialCode: '+976', iso2: 'MN' },
  { name: 'Montenegro', dialCode: '+382', iso2: 'ME' },
  { name: 'Morocco', dialCode: '+212', iso2: 'MO' },
  { name: 'Mozambique', dialCode: '+258', iso2: 'MZ' },
  { name: 'Myanmar', dialCode: '+95', iso2: 'MM' },
  { name: 'Nepal', dialCode: '+977', iso2: 'NP' },
  { name: 'Netherlands', dialCode: '+31', iso2: 'NL' },
  { name: 'New Zealand', dialCode: '+64', iso2: 'NZ' },
  { name: 'Nicaragua', dialCode: '+505', iso2: 'NI' },
  { name: 'Niger', dialCode: '+227', iso2: 'NE' },
  { name: 'Nigeria', dialCode: '+234', iso2: 'NG' },
  { name: 'North Macedonia', dialCode: '+389', iso2: 'MK' },
  { name: 'Norway', dialCode: '+47', iso2: 'NO' },
  { name: 'Oman', dialCode: '+968', iso2: 'OM' },
  { name: 'Pakistan', dialCode: '+92', iso2: 'PK' },
  { name: 'Palestine', dialCode: '+970', iso2: 'PS' },
  { name: 'Panama', dialCode: '+507', iso2: 'PA' },
  { name: 'Paraguay', dialCode: '+595', iso2: 'PY' },
  { name: 'Peru', dialCode: '+51', iso2: 'PE' },
  { name: 'Philippines', dialCode: '+63', iso2: 'PH' },
  { name: 'Poland', dialCode: '+48', iso2: 'PL' },
  { name: 'Portugal', dialCode: '+351', iso2: 'PT' },
  { name: 'Qatar', dialCode: '+974', iso2: 'QA' },
  { name: 'Romania', dialCode: '+40', iso2: 'RO' },
  { name: 'Russia', dialCode: '+7', iso2: 'RU' },
  { name: 'Rwanda', dialCode: '+250', iso2: 'RW' },
  { name: 'Saudi Arabia', dialCode: '+966', iso2: 'SA' },
  { name: 'Senegal', dialCode: '+221', iso2: 'SN' },
  { name: 'Serbia', dialCode: '+381', iso2: 'RS' },
  { name: 'Singapore', dialCode: '+65', iso2: 'SG' },
  { name: 'Slovakia', dialCode: '+421', iso2: 'SK' },
  { name: 'Slovenia', dialCode: '+386', iso2: 'SI' },
  { name: 'South Africa', dialCode: '+27', iso2: 'ZA' },
  { name: 'South Korea', dialCode: '+82', iso2: 'KR' },
  { name: 'Spain', dialCode: '+34', iso2: 'ES' },
  { name: 'Sri Lanka', dialCode: '+94', iso2: 'LK' },
  { name: 'Sudan', dialCode: '+249', iso2: 'SD' },
  { name: 'Sweden', dialCode: '+46', iso2: 'SE' },
  { name: 'Switzerland', dialCode: '+41', iso2: 'CH' },
  { name: 'Syria', dialCode: '+963', iso2: 'SY' },
  { name: 'Taiwan', dialCode: '+886', iso2: 'TW' },
  { name: 'Tanzania', dialCode: '+255', iso2: 'TZ' },
  { name: 'Thailand', dialCode: '+66', iso2: 'TH' },
  { name: 'Tunisia', dialCode: '+216', iso2: 'TN' },
  { name: 'Turkey', dialCode: '+90', iso2: 'TR' },
  { name: 'Uganda', dialCode: '+256', iso2: 'UG' },
  { name: 'Ukraine', dialCode: '+380', iso2: 'UA' },
  { name: 'United Arab Emirates', dialCode: '+971', iso2: 'AE' },
  { name: 'United Kingdom', dialCode: '+44', iso2: 'GB' },
  { name: 'United States', dialCode: '+1', iso2: 'US' },
  { name: 'Uruguay', dialCode: '+598', iso2: 'UY' },
  { name: 'Uzbekistan', dialCode: '+998', iso2: 'UZ' },
  { name: 'Venezuela', dialCode: '+58', iso2: 'VE' },
  { name: 'Vietnam', dialCode: '+84', iso2: 'VN' },
  { name: 'Yemen', dialCode: '+967', iso2: 'YE' },
  { name: 'Zambia', dialCode: '+260', iso2: 'ZM' },
  { name: 'Zimbabwe', dialCode: '+263', iso2: 'ZW' },
];

/**
 * Pre-sorted list: longest dial codes first so prefix matching
 * always picks the most specific entry.
 */
export const COUNTRY_CODES_SORTED = [...COUNTRY_CODES].sort(
  (a, b) => b.dialCode.length - a.dialCode.length,
);
