config:
  # secret: pulumi config set --secret azure-native:subscriptionId <subscription-id>
  azure-native:location: eastus
  tone:provider: azure
  tone:resourceGroup: <aks-resource-group>
  tone:clusterName: <aks-cluster-name>
  tone:namespace: default
  tone:appPool:
    name: apppool
    mode: User
    vmSize: Standard_D2s_v3
    count: 2
    osDiskSizeGb: 128
    enableAutoScaling: true
    minCount: 2
    maxCount: 4
    labels:
      pool: apppool
