# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .get_qstash_endpoint_data import *
from .get_qstash_schedule_data import *
from .get_qstash_schedule_v2_data import *
from .get_qstash_topic_data import *
from .get_qstash_topic_v2_data import *
from .get_redis_database_data import *
from .get_search_data import *
from .get_team_data import *
from .get_vector_index_data import *
from .provider import *
from .qstash_endpoint import *
from .qstash_schedule import *
from .qstash_schedule_v2 import *
from .qstash_topic import *
from .qstash_topic_v2 import *
from .redis_database import *
from .search import *
from .team import *
from .vector_index import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_upstash.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_upstash.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "upstash",
  "mod": "index/qstashEndpoint",
  "fqn": "pulumi_upstash",
  "classes": {
   "upstash:index/qstashEndpoint:QstashEndpoint": "QstashEndpoint"
  }
 },
 {
  "pkg": "upstash",
  "mod": "index/qstashSchedule",
  "fqn": "pulumi_upstash",
  "classes": {
   "upstash:index/qstashSchedule:QstashSchedule": "QstashSchedule"
  }
 },
 {
  "pkg": "upstash",
  "mod": "index/qstashScheduleV2",
  "fqn": "pulumi_upstash",
  "classes": {
   "upstash:index/qstashScheduleV2:QstashScheduleV2": "QstashScheduleV2"
  }
 },
 {
  "pkg": "upstash",
  "mod": "index/qstashTopic",
  "fqn": "pulumi_upstash",
  "classes": {
   "upstash:index/qstashTopic:QstashTopic": "QstashTopic"
  }
 },
 {
  "pkg": "upstash",
  "mod": "index/qstashTopicV2",
  "fqn": "pulumi_upstash",
  "classes": {
   "upstash:index/qstashTopicV2:QstashTopicV2": "QstashTopicV2"
  }
 },
 {
  "pkg": "upstash",
  "mod": "index/redisDatabase",
  "fqn": "pulumi_upstash",
  "classes": {
   "upstash:index/redisDatabase:RedisDatabase": "RedisDatabase"
  }
 },
 {
  "pkg": "upstash",
  "mod": "index/search",
  "fqn": "pulumi_upstash",
  "classes": {
   "upstash:index/search:Search": "Search"
  }
 },
 {
  "pkg": "upstash",
  "mod": "index/team",
  "fqn": "pulumi_upstash",
  "classes": {
   "upstash:index/team:Team": "Team"
  }
 },
 {
  "pkg": "upstash",
  "mod": "index/vectorIndex",
  "fqn": "pulumi_upstash",
  "classes": {
   "upstash:index/vectorIndex:VectorIndex": "VectorIndex"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "upstash",
  "token": "pulumi:providers:upstash",
  "fqn": "pulumi_upstash",
  "class": "Provider"
 }
]
"""
)
