# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetQstashTopicV2DataResult',
    'AwaitableGetQstashTopicV2DataResult',
    'get_qstash_topic_v2_data',
    'get_qstash_topic_v2_data_output',
]

@pulumi.output_type
class GetQstashTopicV2DataResult:
    """
    A collection of values returned by getQstashTopicV2Data.
    """
    def __init__(__self__, created_at=None, endpoints=None, id=None, name=None, updated_at=None):
        if created_at and not isinstance(created_at, float):
            raise TypeError("Expected argument 'created_at' to be a float")
        pulumi.set(__self__, "created_at", created_at)
        if endpoints and not isinstance(endpoints, list):
            raise TypeError("Expected argument 'endpoints' to be a list")
        pulumi.set(__self__, "endpoints", endpoints)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if updated_at and not isinstance(updated_at, float):
            raise TypeError("Expected argument 'updated_at' to be a float")
        pulumi.set(__self__, "updated_at", updated_at)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> _builtins.float:
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter
    def endpoints(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "endpoints")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> _builtins.float:
        return pulumi.get(self, "updated_at")


class AwaitableGetQstashTopicV2DataResult(GetQstashTopicV2DataResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetQstashTopicV2DataResult(
            created_at=self.created_at,
            endpoints=self.endpoints,
            id=self.id,
            name=self.name,
            updated_at=self.updated_at)


def get_qstash_topic_v2_data(id: Optional[_builtins.str] = None,
                             name: Optional[_builtins.str] = None,
                             opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetQstashTopicV2DataResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['name'] = name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('upstash:index/getQstashTopicV2Data:getQstashTopicV2Data', __args__, opts=opts, typ=GetQstashTopicV2DataResult, package_ref=_utilities.get_package()).value

    return AwaitableGetQstashTopicV2DataResult(
        created_at=pulumi.get(__ret__, 'created_at'),
        endpoints=pulumi.get(__ret__, 'endpoints'),
        id=pulumi.get(__ret__, 'id'),
        name=pulumi.get(__ret__, 'name'),
        updated_at=pulumi.get(__ret__, 'updated_at'))
def get_qstash_topic_v2_data_output(id: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                    name: pulumi.Input[Optional[_builtins.str]] = None,
                                    opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetQstashTopicV2DataResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['name'] = name
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('upstash:index/getQstashTopicV2Data:getQstashTopicV2Data', __args__, opts=opts, typ=GetQstashTopicV2DataResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetQstashTopicV2DataResult(
        created_at=pulumi.get(__response__, 'created_at'),
        endpoints=pulumi.get(__response__, 'endpoints'),
        id=pulumi.get(__response__, 'id'),
        name=pulumi.get(__response__, 'name'),
        updated_at=pulumi.get(__response__, 'updated_at')))
