# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetVectorIndexDataResult',
    'AwaitableGetVectorIndexDataResult',
    'get_vector_index_data',
    'get_vector_index_data_output',
]

@pulumi.output_type
class GetVectorIndexDataResult:
    """
    A collection of values returned by getVectorIndexData.
    """
    def __init__(__self__, creation_time=None, customer_id=None, dimension_count=None, endpoint=None, id=None, max_daily_queries=None, max_daily_updates=None, max_monthly_bandwidth=None, max_query_per_second=None, max_reads_per_request=None, max_total_metadata_size=None, max_vector_count=None, max_writes_per_request=None, max_writes_per_second=None, name=None, read_only_token=None, region=None, reserved_price=None, similarity_function=None, token=None, type=None):
        if creation_time and not isinstance(creation_time, float):
            raise TypeError("Expected argument 'creation_time' to be a float")
        pulumi.set(__self__, "creation_time", creation_time)
        if customer_id and not isinstance(customer_id, str):
            raise TypeError("Expected argument 'customer_id' to be a str")
        pulumi.set(__self__, "customer_id", customer_id)
        if dimension_count and not isinstance(dimension_count, float):
            raise TypeError("Expected argument 'dimension_count' to be a float")
        pulumi.set(__self__, "dimension_count", dimension_count)
        if endpoint and not isinstance(endpoint, str):
            raise TypeError("Expected argument 'endpoint' to be a str")
        pulumi.set(__self__, "endpoint", endpoint)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if max_daily_queries and not isinstance(max_daily_queries, float):
            raise TypeError("Expected argument 'max_daily_queries' to be a float")
        pulumi.set(__self__, "max_daily_queries", max_daily_queries)
        if max_daily_updates and not isinstance(max_daily_updates, float):
            raise TypeError("Expected argument 'max_daily_updates' to be a float")
        pulumi.set(__self__, "max_daily_updates", max_daily_updates)
        if max_monthly_bandwidth and not isinstance(max_monthly_bandwidth, float):
            raise TypeError("Expected argument 'max_monthly_bandwidth' to be a float")
        pulumi.set(__self__, "max_monthly_bandwidth", max_monthly_bandwidth)
        if max_query_per_second and not isinstance(max_query_per_second, float):
            raise TypeError("Expected argument 'max_query_per_second' to be a float")
        pulumi.set(__self__, "max_query_per_second", max_query_per_second)
        if max_reads_per_request and not isinstance(max_reads_per_request, float):
            raise TypeError("Expected argument 'max_reads_per_request' to be a float")
        pulumi.set(__self__, "max_reads_per_request", max_reads_per_request)
        if max_total_metadata_size and not isinstance(max_total_metadata_size, float):
            raise TypeError("Expected argument 'max_total_metadata_size' to be a float")
        pulumi.set(__self__, "max_total_metadata_size", max_total_metadata_size)
        if max_vector_count and not isinstance(max_vector_count, float):
            raise TypeError("Expected argument 'max_vector_count' to be a float")
        pulumi.set(__self__, "max_vector_count", max_vector_count)
        if max_writes_per_request and not isinstance(max_writes_per_request, float):
            raise TypeError("Expected argument 'max_writes_per_request' to be a float")
        pulumi.set(__self__, "max_writes_per_request", max_writes_per_request)
        if max_writes_per_second and not isinstance(max_writes_per_second, float):
            raise TypeError("Expected argument 'max_writes_per_second' to be a float")
        pulumi.set(__self__, "max_writes_per_second", max_writes_per_second)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if read_only_token and not isinstance(read_only_token, str):
            raise TypeError("Expected argument 'read_only_token' to be a str")
        pulumi.set(__self__, "read_only_token", read_only_token)
        if region and not isinstance(region, str):
            raise TypeError("Expected argument 'region' to be a str")
        pulumi.set(__self__, "region", region)
        if reserved_price and not isinstance(reserved_price, float):
            raise TypeError("Expected argument 'reserved_price' to be a float")
        pulumi.set(__self__, "reserved_price", reserved_price)
        if similarity_function and not isinstance(similarity_function, str):
            raise TypeError("Expected argument 'similarity_function' to be a str")
        pulumi.set(__self__, "similarity_function", similarity_function)
        if token and not isinstance(token, str):
            raise TypeError("Expected argument 'token' to be a str")
        pulumi.set(__self__, "token", token)
        if type and not isinstance(type, str):
            raise TypeError("Expected argument 'type' to be a str")
        pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter(name="creationTime")
    def creation_time(self) -> _builtins.float:
        return pulumi.get(self, "creation_time")

    @_builtins.property
    @pulumi.getter(name="customerId")
    def customer_id(self) -> _builtins.str:
        return pulumi.get(self, "customer_id")

    @_builtins.property
    @pulumi.getter(name="dimensionCount")
    def dimension_count(self) -> _builtins.float:
        return pulumi.get(self, "dimension_count")

    @_builtins.property
    @pulumi.getter
    def endpoint(self) -> _builtins.str:
        return pulumi.get(self, "endpoint")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="maxDailyQueries")
    def max_daily_queries(self) -> _builtins.float:
        return pulumi.get(self, "max_daily_queries")

    @_builtins.property
    @pulumi.getter(name="maxDailyUpdates")
    def max_daily_updates(self) -> _builtins.float:
        return pulumi.get(self, "max_daily_updates")

    @_builtins.property
    @pulumi.getter(name="maxMonthlyBandwidth")
    def max_monthly_bandwidth(self) -> _builtins.float:
        return pulumi.get(self, "max_monthly_bandwidth")

    @_builtins.property
    @pulumi.getter(name="maxQueryPerSecond")
    def max_query_per_second(self) -> _builtins.float:
        return pulumi.get(self, "max_query_per_second")

    @_builtins.property
    @pulumi.getter(name="maxReadsPerRequest")
    def max_reads_per_request(self) -> _builtins.float:
        return pulumi.get(self, "max_reads_per_request")

    @_builtins.property
    @pulumi.getter(name="maxTotalMetadataSize")
    def max_total_metadata_size(self) -> _builtins.float:
        return pulumi.get(self, "max_total_metadata_size")

    @_builtins.property
    @pulumi.getter(name="maxVectorCount")
    def max_vector_count(self) -> _builtins.float:
        return pulumi.get(self, "max_vector_count")

    @_builtins.property
    @pulumi.getter(name="maxWritesPerRequest")
    def max_writes_per_request(self) -> _builtins.float:
        return pulumi.get(self, "max_writes_per_request")

    @_builtins.property
    @pulumi.getter(name="maxWritesPerSecond")
    def max_writes_per_second(self) -> _builtins.float:
        return pulumi.get(self, "max_writes_per_second")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="readOnlyToken")
    def read_only_token(self) -> _builtins.str:
        return pulumi.get(self, "read_only_token")

    @_builtins.property
    @pulumi.getter
    def region(self) -> _builtins.str:
        return pulumi.get(self, "region")

    @_builtins.property
    @pulumi.getter(name="reservedPrice")
    def reserved_price(self) -> _builtins.float:
        return pulumi.get(self, "reserved_price")

    @_builtins.property
    @pulumi.getter(name="similarityFunction")
    def similarity_function(self) -> _builtins.str:
        return pulumi.get(self, "similarity_function")

    @_builtins.property
    @pulumi.getter
    def token(self) -> _builtins.str:
        return pulumi.get(self, "token")

    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str:
        return pulumi.get(self, "type")


class AwaitableGetVectorIndexDataResult(GetVectorIndexDataResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetVectorIndexDataResult(
            creation_time=self.creation_time,
            customer_id=self.customer_id,
            dimension_count=self.dimension_count,
            endpoint=self.endpoint,
            id=self.id,
            max_daily_queries=self.max_daily_queries,
            max_daily_updates=self.max_daily_updates,
            max_monthly_bandwidth=self.max_monthly_bandwidth,
            max_query_per_second=self.max_query_per_second,
            max_reads_per_request=self.max_reads_per_request,
            max_total_metadata_size=self.max_total_metadata_size,
            max_vector_count=self.max_vector_count,
            max_writes_per_request=self.max_writes_per_request,
            max_writes_per_second=self.max_writes_per_second,
            name=self.name,
            read_only_token=self.read_only_token,
            region=self.region,
            reserved_price=self.reserved_price,
            similarity_function=self.similarity_function,
            token=self.token,
            type=self.type)


def get_vector_index_data(id: Optional[_builtins.str] = None,
                          opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetVectorIndexDataResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('upstash:index/getVectorIndexData:getVectorIndexData', __args__, opts=opts, typ=GetVectorIndexDataResult, package_ref=_utilities.get_package()).value

    return AwaitableGetVectorIndexDataResult(
        creation_time=pulumi.get(__ret__, 'creation_time'),
        customer_id=pulumi.get(__ret__, 'customer_id'),
        dimension_count=pulumi.get(__ret__, 'dimension_count'),
        endpoint=pulumi.get(__ret__, 'endpoint'),
        id=pulumi.get(__ret__, 'id'),
        max_daily_queries=pulumi.get(__ret__, 'max_daily_queries'),
        max_daily_updates=pulumi.get(__ret__, 'max_daily_updates'),
        max_monthly_bandwidth=pulumi.get(__ret__, 'max_monthly_bandwidth'),
        max_query_per_second=pulumi.get(__ret__, 'max_query_per_second'),
        max_reads_per_request=pulumi.get(__ret__, 'max_reads_per_request'),
        max_total_metadata_size=pulumi.get(__ret__, 'max_total_metadata_size'),
        max_vector_count=pulumi.get(__ret__, 'max_vector_count'),
        max_writes_per_request=pulumi.get(__ret__, 'max_writes_per_request'),
        max_writes_per_second=pulumi.get(__ret__, 'max_writes_per_second'),
        name=pulumi.get(__ret__, 'name'),
        read_only_token=pulumi.get(__ret__, 'read_only_token'),
        region=pulumi.get(__ret__, 'region'),
        reserved_price=pulumi.get(__ret__, 'reserved_price'),
        similarity_function=pulumi.get(__ret__, 'similarity_function'),
        token=pulumi.get(__ret__, 'token'),
        type=pulumi.get(__ret__, 'type'))
def get_vector_index_data_output(id: pulumi.Input[Optional[_builtins.str]] = None,
                                 opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetVectorIndexDataResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('upstash:index/getVectorIndexData:getVectorIndexData', __args__, opts=opts, typ=GetVectorIndexDataResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetVectorIndexDataResult(
        creation_time=pulumi.get(__response__, 'creation_time'),
        customer_id=pulumi.get(__response__, 'customer_id'),
        dimension_count=pulumi.get(__response__, 'dimension_count'),
        endpoint=pulumi.get(__response__, 'endpoint'),
        id=pulumi.get(__response__, 'id'),
        max_daily_queries=pulumi.get(__response__, 'max_daily_queries'),
        max_daily_updates=pulumi.get(__response__, 'max_daily_updates'),
        max_monthly_bandwidth=pulumi.get(__response__, 'max_monthly_bandwidth'),
        max_query_per_second=pulumi.get(__response__, 'max_query_per_second'),
        max_reads_per_request=pulumi.get(__response__, 'max_reads_per_request'),
        max_total_metadata_size=pulumi.get(__response__, 'max_total_metadata_size'),
        max_vector_count=pulumi.get(__response__, 'max_vector_count'),
        max_writes_per_request=pulumi.get(__response__, 'max_writes_per_request'),
        max_writes_per_second=pulumi.get(__response__, 'max_writes_per_second'),
        name=pulumi.get(__response__, 'name'),
        read_only_token=pulumi.get(__response__, 'read_only_token'),
        region=pulumi.get(__response__, 'region'),
        reserved_price=pulumi.get(__response__, 'reserved_price'),
        similarity_function=pulumi.get(__response__, 'similarity_function'),
        token=pulumi.get(__response__, 'token'),
        type=pulumi.get(__response__, 'type')))
