# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetTeamDataResult',
    'AwaitableGetTeamDataResult',
    'get_team_data',
    'get_team_data_output',
]

@pulumi.output_type
class GetTeamDataResult:
    """
    A collection of values returned by getTeamData.
    """
    def __init__(__self__, copy_cc=None, id=None, team_id=None, team_members=None, team_name=None):
        if copy_cc and not isinstance(copy_cc, bool):
            raise TypeError("Expected argument 'copy_cc' to be a bool")
        pulumi.set(__self__, "copy_cc", copy_cc)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if team_id and not isinstance(team_id, str):
            raise TypeError("Expected argument 'team_id' to be a str")
        pulumi.set(__self__, "team_id", team_id)
        if team_members and not isinstance(team_members, dict):
            raise TypeError("Expected argument 'team_members' to be a dict")
        pulumi.set(__self__, "team_members", team_members)
        if team_name and not isinstance(team_name, str):
            raise TypeError("Expected argument 'team_name' to be a str")
        pulumi.set(__self__, "team_name", team_name)

    @_builtins.property
    @pulumi.getter(name="copyCc")
    def copy_cc(self) -> _builtins.bool:
        return pulumi.get(self, "copy_cc")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="teamId")
    def team_id(self) -> _builtins.str:
        return pulumi.get(self, "team_id")

    @_builtins.property
    @pulumi.getter(name="teamMembers")
    def team_members(self) -> Mapping[str, _builtins.str]:
        return pulumi.get(self, "team_members")

    @_builtins.property
    @pulumi.getter(name="teamName")
    def team_name(self) -> _builtins.str:
        return pulumi.get(self, "team_name")


class AwaitableGetTeamDataResult(GetTeamDataResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetTeamDataResult(
            copy_cc=self.copy_cc,
            id=self.id,
            team_id=self.team_id,
            team_members=self.team_members,
            team_name=self.team_name)


def get_team_data(id: Optional[_builtins.str] = None,
                  team_id: Optional[_builtins.str] = None,
                  opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetTeamDataResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['teamId'] = team_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('upstash:index/getTeamData:getTeamData', __args__, opts=opts, typ=GetTeamDataResult, package_ref=_utilities.get_package()).value

    return AwaitableGetTeamDataResult(
        copy_cc=pulumi.get(__ret__, 'copy_cc'),
        id=pulumi.get(__ret__, 'id'),
        team_id=pulumi.get(__ret__, 'team_id'),
        team_members=pulumi.get(__ret__, 'team_members'),
        team_name=pulumi.get(__ret__, 'team_name'))
def get_team_data_output(id: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                         team_id: pulumi.Input[Optional[_builtins.str]] = None,
                         opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetTeamDataResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['teamId'] = team_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('upstash:index/getTeamData:getTeamData', __args__, opts=opts, typ=GetTeamDataResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetTeamDataResult(
        copy_cc=pulumi.get(__response__, 'copy_cc'),
        id=pulumi.get(__response__, 'id'),
        team_id=pulumi.get(__response__, 'team_id'),
        team_members=pulumi.get(__response__, 'team_members'),
        team_name=pulumi.get(__response__, 'team_name')))
