# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['QstashTopicArgs', 'QstashTopic']

@pulumi.input_type
class QstashTopicArgs:
    def __init__(__self__, *,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 qstash_topic_id: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a QstashTopic resource.

        :param pulumi.Input[_builtins.str] name: Name of the Qstash Topic
        """
        if name is not None:
            pulumi.set(__self__, "name", name)
        if qstash_topic_id is not None:
            pulumi.set(__self__, "qstash_topic_id", qstash_topic_id)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Name of the Qstash Topic
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="qstashTopicId")
    def qstash_topic_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "qstash_topic_id")

    @qstash_topic_id.setter
    def qstash_topic_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "qstash_topic_id", value)


@pulumi.input_type
class _QstashTopicState:
    def __init__(__self__, *,
                 endpoints: pulumi.Input[Optional[Sequence[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 qstash_topic_id: pulumi.Input[Optional[_builtins.str]] = None,
                 topic_id: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering QstashTopic resources.

        :param pulumi.Input[Sequence[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]] endpoints: Endpoints for the Qstash Topic
        :param pulumi.Input[_builtins.str] name: Name of the Qstash Topic
        :param pulumi.Input[_builtins.str] topic_id: Unique Qstash Topic ID for requested topic
        """
        if endpoints is not None:
            pulumi.set(__self__, "endpoints", endpoints)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if qstash_topic_id is not None:
            pulumi.set(__self__, "qstash_topic_id", qstash_topic_id)
        if topic_id is not None:
            pulumi.set(__self__, "topic_id", topic_id)

    @_builtins.property
    @pulumi.getter
    def endpoints(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]]]:
        """
        Endpoints for the Qstash Topic
        """
        return pulumi.get(self, "endpoints")

    @endpoints.setter
    def endpoints(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]]]):
        pulumi.set(self, "endpoints", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Name of the Qstash Topic
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="qstashTopicId")
    def qstash_topic_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "qstash_topic_id")

    @qstash_topic_id.setter
    def qstash_topic_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "qstash_topic_id", value)

    @_builtins.property
    @pulumi.getter(name="topicId")
    def topic_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Unique Qstash Topic ID for requested topic
        """
        return pulumi.get(self, "topic_id")

    @topic_id.setter
    def topic_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "topic_id", value)


@pulumi.type_token("upstash:index/qstashTopic:QstashTopic")
class QstashTopic(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 qstash_topic_id: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Create a QstashTopic resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] name: Name of the Qstash Topic
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[QstashTopicArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a QstashTopic resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param QstashTopicArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(QstashTopicArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 qstash_topic_id: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = QstashTopicArgs.__new__(QstashTopicArgs)

            __props__.__dict__["name"] = name
            __props__.__dict__["qstash_topic_id"] = qstash_topic_id
            __props__.__dict__["endpoints"] = None
            __props__.__dict__["topic_id"] = None
        super(QstashTopic, __self__).__init__(
            'upstash:index/qstashTopic:QstashTopic',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            endpoints: pulumi.Input[Optional[Sequence[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            qstash_topic_id: pulumi.Input[Optional[_builtins.str]] = None,
            topic_id: pulumi.Input[Optional[_builtins.str]] = None) -> 'QstashTopic':
        """
        Get an existing QstashTopic resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]] endpoints: Endpoints for the Qstash Topic
        :param pulumi.Input[_builtins.str] name: Name of the Qstash Topic
        :param pulumi.Input[_builtins.str] topic_id: Unique Qstash Topic ID for requested topic
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _QstashTopicState.__new__(_QstashTopicState)

        __props__.__dict__["endpoints"] = endpoints
        __props__.__dict__["name"] = name
        __props__.__dict__["qstash_topic_id"] = qstash_topic_id
        __props__.__dict__["topic_id"] = topic_id
        return QstashTopic(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def endpoints(self) -> pulumi.Output[Sequence[Mapping[str, _builtins.str]]]:
        """
        Endpoints for the Qstash Topic
        """
        return pulumi.get(self, "endpoints")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Name of the Qstash Topic
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="qstashTopicId")
    def qstash_topic_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "qstash_topic_id")

    @_builtins.property
    @pulumi.getter(name="topicId")
    def topic_id(self) -> pulumi.Output[_builtins.str]:
        """
        Unique Qstash Topic ID for requested topic
        """
        return pulumi.get(self, "topic_id")

