# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['QstashScheduleArgs', 'QstashSchedule']

@pulumi.input_type
class QstashScheduleArgs:
    def __init__(__self__, *,
                 cron: pulumi.Input[_builtins.str],
                 destination: pulumi.Input[_builtins.str],
                 body: pulumi.Input[Optional[_builtins.str]] = None,
                 callback: pulumi.Input[Optional[_builtins.str]] = None,
                 content_based_deduplication: pulumi.Input[Optional[_builtins.bool]] = None,
                 content_type: pulumi.Input[Optional[_builtins.str]] = None,
                 deduplication_id: pulumi.Input[Optional[_builtins.str]] = None,
                 delay: pulumi.Input[Optional[_builtins.str]] = None,
                 forward_headers: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 not_before: pulumi.Input[Optional[_builtins.float]] = None,
                 qstash_schedule_id: pulumi.Input[Optional[_builtins.str]] = None,
                 retries: pulumi.Input[Optional[_builtins.float]] = None):
        """
        The set of arguments for constructing a QstashSchedule resource.

        :param pulumi.Input[_builtins.str] cron: Cron string for Qstash Schedule
        :param pulumi.Input[_builtins.str] destination: Destination for Qstash Schedule. Either Topic ID or valid URL
        :param pulumi.Input[_builtins.str] body: Body to send for the POST request in string format. Needs escaping (\\) double quotes.
        :param pulumi.Input[_builtins.str] callback: Callback URL for Qstash Schedule.
        :param pulumi.Input[_builtins.bool] content_based_deduplication: Content Based Deduplication (bool) for Qstash Scheduling.
        :param pulumi.Input[_builtins.str] content_type: Content type for Qstash Scheduling.
        :param pulumi.Input[_builtins.str] deduplication_id: Deduplication ID for Qstash Scheduling.
        :param pulumi.Input[_builtins.str] delay: Delay for Qstash Schedule.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] forward_headers: Forward headers to your API
        :param pulumi.Input[_builtins.float] not_before: Start time for Qstash Scheduling.
        :param pulumi.Input[_builtins.float] retries: Retries for Qstash Schedule requests.
        """
        pulumi.set(__self__, "cron", cron)
        pulumi.set(__self__, "destination", destination)
        if body is not None:
            pulumi.set(__self__, "body", body)
        if callback is not None:
            pulumi.set(__self__, "callback", callback)
        if content_based_deduplication is not None:
            pulumi.set(__self__, "content_based_deduplication", content_based_deduplication)
        if content_type is not None:
            pulumi.set(__self__, "content_type", content_type)
        if deduplication_id is not None:
            pulumi.set(__self__, "deduplication_id", deduplication_id)
        if delay is not None:
            pulumi.set(__self__, "delay", delay)
        if forward_headers is not None:
            pulumi.set(__self__, "forward_headers", forward_headers)
        if not_before is not None:
            pulumi.set(__self__, "not_before", not_before)
        if qstash_schedule_id is not None:
            pulumi.set(__self__, "qstash_schedule_id", qstash_schedule_id)
        if retries is not None:
            pulumi.set(__self__, "retries", retries)

    @_builtins.property
    @pulumi.getter
    def cron(self) -> pulumi.Input[_builtins.str]:
        """
        Cron string for Qstash Schedule
        """
        return pulumi.get(self, "cron")

    @cron.setter
    def cron(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "cron", value)

    @_builtins.property
    @pulumi.getter
    def destination(self) -> pulumi.Input[_builtins.str]:
        """
        Destination for Qstash Schedule. Either Topic ID or valid URL
        """
        return pulumi.get(self, "destination")

    @destination.setter
    def destination(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "destination", value)

    @_builtins.property
    @pulumi.getter
    def body(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Body to send for the POST request in string format. Needs escaping (\\) double quotes.
        """
        return pulumi.get(self, "body")

    @body.setter
    def body(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "body", value)

    @_builtins.property
    @pulumi.getter
    def callback(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Callback URL for Qstash Schedule.
        """
        return pulumi.get(self, "callback")

    @callback.setter
    def callback(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "callback", value)

    @_builtins.property
    @pulumi.getter(name="contentBasedDeduplication")
    def content_based_deduplication(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Content Based Deduplication (bool) for Qstash Scheduling.
        """
        return pulumi.get(self, "content_based_deduplication")

    @content_based_deduplication.setter
    def content_based_deduplication(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "content_based_deduplication", value)

    @_builtins.property
    @pulumi.getter(name="contentType")
    def content_type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Content type for Qstash Scheduling.
        """
        return pulumi.get(self, "content_type")

    @content_type.setter
    def content_type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "content_type", value)

    @_builtins.property
    @pulumi.getter(name="deduplicationId")
    def deduplication_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Deduplication ID for Qstash Scheduling.
        """
        return pulumi.get(self, "deduplication_id")

    @deduplication_id.setter
    def deduplication_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "deduplication_id", value)

    @_builtins.property
    @pulumi.getter
    def delay(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Delay for Qstash Schedule.
        """
        return pulumi.get(self, "delay")

    @delay.setter
    def delay(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "delay", value)

    @_builtins.property
    @pulumi.getter(name="forwardHeaders")
    def forward_headers(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Forward headers to your API
        """
        return pulumi.get(self, "forward_headers")

    @forward_headers.setter
    def forward_headers(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "forward_headers", value)

    @_builtins.property
    @pulumi.getter(name="notBefore")
    def not_before(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Start time for Qstash Scheduling.
        """
        return pulumi.get(self, "not_before")

    @not_before.setter
    def not_before(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "not_before", value)

    @_builtins.property
    @pulumi.getter(name="qstashScheduleId")
    def qstash_schedule_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "qstash_schedule_id")

    @qstash_schedule_id.setter
    def qstash_schedule_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "qstash_schedule_id", value)

    @_builtins.property
    @pulumi.getter
    def retries(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Retries for Qstash Schedule requests.
        """
        return pulumi.get(self, "retries")

    @retries.setter
    def retries(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "retries", value)


@pulumi.input_type
class _QstashScheduleState:
    def __init__(__self__, *,
                 body: pulumi.Input[Optional[_builtins.str]] = None,
                 callback: pulumi.Input[Optional[_builtins.str]] = None,
                 content_based_deduplication: pulumi.Input[Optional[_builtins.bool]] = None,
                 content_type: pulumi.Input[Optional[_builtins.str]] = None,
                 created_at: pulumi.Input[Optional[_builtins.float]] = None,
                 cron: pulumi.Input[Optional[_builtins.str]] = None,
                 deduplication_id: pulumi.Input[Optional[_builtins.str]] = None,
                 delay: pulumi.Input[Optional[_builtins.str]] = None,
                 destination: pulumi.Input[Optional[_builtins.str]] = None,
                 forward_headers: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 not_before: pulumi.Input[Optional[_builtins.float]] = None,
                 qstash_schedule_id: pulumi.Input[Optional[_builtins.str]] = None,
                 retries: pulumi.Input[Optional[_builtins.float]] = None,
                 schedule_id: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering QstashSchedule resources.

        :param pulumi.Input[_builtins.str] body: Body to send for the POST request in string format. Needs escaping (\\) double quotes.
        :param pulumi.Input[_builtins.str] callback: Callback URL for Qstash Schedule.
        :param pulumi.Input[_builtins.bool] content_based_deduplication: Content Based Deduplication (bool) for Qstash Scheduling.
        :param pulumi.Input[_builtins.str] content_type: Content type for Qstash Scheduling.
        :param pulumi.Input[_builtins.float] created_at: Creation time for Qstash Schedule.
        :param pulumi.Input[_builtins.str] cron: Cron string for Qstash Schedule
        :param pulumi.Input[_builtins.str] deduplication_id: Deduplication ID for Qstash Scheduling.
        :param pulumi.Input[_builtins.str] delay: Delay for Qstash Schedule.
        :param pulumi.Input[_builtins.str] destination: Destination for Qstash Schedule. Either Topic ID or valid URL
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] forward_headers: Forward headers to your API
        :param pulumi.Input[_builtins.float] not_before: Start time for Qstash Scheduling.
        :param pulumi.Input[_builtins.float] retries: Retries for Qstash Schedule requests.
        :param pulumi.Input[_builtins.str] schedule_id: Unique Qstash Schedule ID for requested schedule
        """
        if body is not None:
            pulumi.set(__self__, "body", body)
        if callback is not None:
            pulumi.set(__self__, "callback", callback)
        if content_based_deduplication is not None:
            pulumi.set(__self__, "content_based_deduplication", content_based_deduplication)
        if content_type is not None:
            pulumi.set(__self__, "content_type", content_type)
        if created_at is not None:
            pulumi.set(__self__, "created_at", created_at)
        if cron is not None:
            pulumi.set(__self__, "cron", cron)
        if deduplication_id is not None:
            pulumi.set(__self__, "deduplication_id", deduplication_id)
        if delay is not None:
            pulumi.set(__self__, "delay", delay)
        if destination is not None:
            pulumi.set(__self__, "destination", destination)
        if forward_headers is not None:
            pulumi.set(__self__, "forward_headers", forward_headers)
        if not_before is not None:
            pulumi.set(__self__, "not_before", not_before)
        if qstash_schedule_id is not None:
            pulumi.set(__self__, "qstash_schedule_id", qstash_schedule_id)
        if retries is not None:
            pulumi.set(__self__, "retries", retries)
        if schedule_id is not None:
            pulumi.set(__self__, "schedule_id", schedule_id)

    @_builtins.property
    @pulumi.getter
    def body(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Body to send for the POST request in string format. Needs escaping (\\) double quotes.
        """
        return pulumi.get(self, "body")

    @body.setter
    def body(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "body", value)

    @_builtins.property
    @pulumi.getter
    def callback(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Callback URL for Qstash Schedule.
        """
        return pulumi.get(self, "callback")

    @callback.setter
    def callback(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "callback", value)

    @_builtins.property
    @pulumi.getter(name="contentBasedDeduplication")
    def content_based_deduplication(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Content Based Deduplication (bool) for Qstash Scheduling.
        """
        return pulumi.get(self, "content_based_deduplication")

    @content_based_deduplication.setter
    def content_based_deduplication(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "content_based_deduplication", value)

    @_builtins.property
    @pulumi.getter(name="contentType")
    def content_type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Content type for Qstash Scheduling.
        """
        return pulumi.get(self, "content_type")

    @content_type.setter
    def content_type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "content_type", value)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Creation time for Qstash Schedule.
        """
        return pulumi.get(self, "created_at")

    @created_at.setter
    def created_at(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "created_at", value)

    @_builtins.property
    @pulumi.getter
    def cron(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Cron string for Qstash Schedule
        """
        return pulumi.get(self, "cron")

    @cron.setter
    def cron(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "cron", value)

    @_builtins.property
    @pulumi.getter(name="deduplicationId")
    def deduplication_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Deduplication ID for Qstash Scheduling.
        """
        return pulumi.get(self, "deduplication_id")

    @deduplication_id.setter
    def deduplication_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "deduplication_id", value)

    @_builtins.property
    @pulumi.getter
    def delay(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Delay for Qstash Schedule.
        """
        return pulumi.get(self, "delay")

    @delay.setter
    def delay(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "delay", value)

    @_builtins.property
    @pulumi.getter
    def destination(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Destination for Qstash Schedule. Either Topic ID or valid URL
        """
        return pulumi.get(self, "destination")

    @destination.setter
    def destination(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "destination", value)

    @_builtins.property
    @pulumi.getter(name="forwardHeaders")
    def forward_headers(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Forward headers to your API
        """
        return pulumi.get(self, "forward_headers")

    @forward_headers.setter
    def forward_headers(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "forward_headers", value)

    @_builtins.property
    @pulumi.getter(name="notBefore")
    def not_before(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Start time for Qstash Scheduling.
        """
        return pulumi.get(self, "not_before")

    @not_before.setter
    def not_before(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "not_before", value)

    @_builtins.property
    @pulumi.getter(name="qstashScheduleId")
    def qstash_schedule_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "qstash_schedule_id")

    @qstash_schedule_id.setter
    def qstash_schedule_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "qstash_schedule_id", value)

    @_builtins.property
    @pulumi.getter
    def retries(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Retries for Qstash Schedule requests.
        """
        return pulumi.get(self, "retries")

    @retries.setter
    def retries(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "retries", value)

    @_builtins.property
    @pulumi.getter(name="scheduleId")
    def schedule_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Unique Qstash Schedule ID for requested schedule
        """
        return pulumi.get(self, "schedule_id")

    @schedule_id.setter
    def schedule_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "schedule_id", value)


@pulumi.type_token("upstash:index/qstashSchedule:QstashSchedule")
class QstashSchedule(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 body: pulumi.Input[Optional[_builtins.str]] = None,
                 callback: pulumi.Input[Optional[_builtins.str]] = None,
                 content_based_deduplication: pulumi.Input[Optional[_builtins.bool]] = None,
                 content_type: pulumi.Input[Optional[_builtins.str]] = None,
                 cron: pulumi.Input[Optional[_builtins.str]] = None,
                 deduplication_id: pulumi.Input[Optional[_builtins.str]] = None,
                 delay: pulumi.Input[Optional[_builtins.str]] = None,
                 destination: pulumi.Input[Optional[_builtins.str]] = None,
                 forward_headers: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 not_before: pulumi.Input[Optional[_builtins.float]] = None,
                 qstash_schedule_id: pulumi.Input[Optional[_builtins.str]] = None,
                 retries: pulumi.Input[Optional[_builtins.float]] = None,
                 __props__=None):
        """
        Create a QstashSchedule resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] body: Body to send for the POST request in string format. Needs escaping (\\) double quotes.
        :param pulumi.Input[_builtins.str] callback: Callback URL for Qstash Schedule.
        :param pulumi.Input[_builtins.bool] content_based_deduplication: Content Based Deduplication (bool) for Qstash Scheduling.
        :param pulumi.Input[_builtins.str] content_type: Content type for Qstash Scheduling.
        :param pulumi.Input[_builtins.str] cron: Cron string for Qstash Schedule
        :param pulumi.Input[_builtins.str] deduplication_id: Deduplication ID for Qstash Scheduling.
        :param pulumi.Input[_builtins.str] delay: Delay for Qstash Schedule.
        :param pulumi.Input[_builtins.str] destination: Destination for Qstash Schedule. Either Topic ID or valid URL
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] forward_headers: Forward headers to your API
        :param pulumi.Input[_builtins.float] not_before: Start time for Qstash Scheduling.
        :param pulumi.Input[_builtins.float] retries: Retries for Qstash Schedule requests.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: QstashScheduleArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a QstashSchedule resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param QstashScheduleArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(QstashScheduleArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 body: pulumi.Input[Optional[_builtins.str]] = None,
                 callback: pulumi.Input[Optional[_builtins.str]] = None,
                 content_based_deduplication: pulumi.Input[Optional[_builtins.bool]] = None,
                 content_type: pulumi.Input[Optional[_builtins.str]] = None,
                 cron: pulumi.Input[Optional[_builtins.str]] = None,
                 deduplication_id: pulumi.Input[Optional[_builtins.str]] = None,
                 delay: pulumi.Input[Optional[_builtins.str]] = None,
                 destination: pulumi.Input[Optional[_builtins.str]] = None,
                 forward_headers: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 not_before: pulumi.Input[Optional[_builtins.float]] = None,
                 qstash_schedule_id: pulumi.Input[Optional[_builtins.str]] = None,
                 retries: pulumi.Input[Optional[_builtins.float]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = QstashScheduleArgs.__new__(QstashScheduleArgs)

            __props__.__dict__["body"] = body
            __props__.__dict__["callback"] = callback
            __props__.__dict__["content_based_deduplication"] = content_based_deduplication
            __props__.__dict__["content_type"] = content_type
            if cron is None and not opts.urn:
                raise TypeError("Missing required property 'cron'")
            __props__.__dict__["cron"] = cron
            __props__.__dict__["deduplication_id"] = deduplication_id
            __props__.__dict__["delay"] = delay
            if destination is None and not opts.urn:
                raise TypeError("Missing required property 'destination'")
            __props__.__dict__["destination"] = destination
            __props__.__dict__["forward_headers"] = forward_headers
            __props__.__dict__["not_before"] = not_before
            __props__.__dict__["qstash_schedule_id"] = qstash_schedule_id
            __props__.__dict__["retries"] = retries
            __props__.__dict__["created_at"] = None
            __props__.__dict__["schedule_id"] = None
        super(QstashSchedule, __self__).__init__(
            'upstash:index/qstashSchedule:QstashSchedule',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            body: pulumi.Input[Optional[_builtins.str]] = None,
            callback: pulumi.Input[Optional[_builtins.str]] = None,
            content_based_deduplication: pulumi.Input[Optional[_builtins.bool]] = None,
            content_type: pulumi.Input[Optional[_builtins.str]] = None,
            created_at: pulumi.Input[Optional[_builtins.float]] = None,
            cron: pulumi.Input[Optional[_builtins.str]] = None,
            deduplication_id: pulumi.Input[Optional[_builtins.str]] = None,
            delay: pulumi.Input[Optional[_builtins.str]] = None,
            destination: pulumi.Input[Optional[_builtins.str]] = None,
            forward_headers: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
            not_before: pulumi.Input[Optional[_builtins.float]] = None,
            qstash_schedule_id: pulumi.Input[Optional[_builtins.str]] = None,
            retries: pulumi.Input[Optional[_builtins.float]] = None,
            schedule_id: pulumi.Input[Optional[_builtins.str]] = None) -> 'QstashSchedule':
        """
        Get an existing QstashSchedule resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] body: Body to send for the POST request in string format. Needs escaping (\\) double quotes.
        :param pulumi.Input[_builtins.str] callback: Callback URL for Qstash Schedule.
        :param pulumi.Input[_builtins.bool] content_based_deduplication: Content Based Deduplication (bool) for Qstash Scheduling.
        :param pulumi.Input[_builtins.str] content_type: Content type for Qstash Scheduling.
        :param pulumi.Input[_builtins.float] created_at: Creation time for Qstash Schedule.
        :param pulumi.Input[_builtins.str] cron: Cron string for Qstash Schedule
        :param pulumi.Input[_builtins.str] deduplication_id: Deduplication ID for Qstash Scheduling.
        :param pulumi.Input[_builtins.str] delay: Delay for Qstash Schedule.
        :param pulumi.Input[_builtins.str] destination: Destination for Qstash Schedule. Either Topic ID or valid URL
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] forward_headers: Forward headers to your API
        :param pulumi.Input[_builtins.float] not_before: Start time for Qstash Scheduling.
        :param pulumi.Input[_builtins.float] retries: Retries for Qstash Schedule requests.
        :param pulumi.Input[_builtins.str] schedule_id: Unique Qstash Schedule ID for requested schedule
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _QstashScheduleState.__new__(_QstashScheduleState)

        __props__.__dict__["body"] = body
        __props__.__dict__["callback"] = callback
        __props__.__dict__["content_based_deduplication"] = content_based_deduplication
        __props__.__dict__["content_type"] = content_type
        __props__.__dict__["created_at"] = created_at
        __props__.__dict__["cron"] = cron
        __props__.__dict__["deduplication_id"] = deduplication_id
        __props__.__dict__["delay"] = delay
        __props__.__dict__["destination"] = destination
        __props__.__dict__["forward_headers"] = forward_headers
        __props__.__dict__["not_before"] = not_before
        __props__.__dict__["qstash_schedule_id"] = qstash_schedule_id
        __props__.__dict__["retries"] = retries
        __props__.__dict__["schedule_id"] = schedule_id
        return QstashSchedule(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def body(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Body to send for the POST request in string format. Needs escaping (\\) double quotes.
        """
        return pulumi.get(self, "body")

    @_builtins.property
    @pulumi.getter
    def callback(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Callback URL for Qstash Schedule.
        """
        return pulumi.get(self, "callback")

    @_builtins.property
    @pulumi.getter(name="contentBasedDeduplication")
    def content_based_deduplication(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Content Based Deduplication (bool) for Qstash Scheduling.
        """
        return pulumi.get(self, "content_based_deduplication")

    @_builtins.property
    @pulumi.getter(name="contentType")
    def content_type(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Content type for Qstash Scheduling.
        """
        return pulumi.get(self, "content_type")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[_builtins.float]:
        """
        Creation time for Qstash Schedule.
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter
    def cron(self) -> pulumi.Output[_builtins.str]:
        """
        Cron string for Qstash Schedule
        """
        return pulumi.get(self, "cron")

    @_builtins.property
    @pulumi.getter(name="deduplicationId")
    def deduplication_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Deduplication ID for Qstash Scheduling.
        """
        return pulumi.get(self, "deduplication_id")

    @_builtins.property
    @pulumi.getter
    def delay(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Delay for Qstash Schedule.
        """
        return pulumi.get(self, "delay")

    @_builtins.property
    @pulumi.getter
    def destination(self) -> pulumi.Output[_builtins.str]:
        """
        Destination for Qstash Schedule. Either Topic ID or valid URL
        """
        return pulumi.get(self, "destination")

    @_builtins.property
    @pulumi.getter(name="forwardHeaders")
    def forward_headers(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        """
        Forward headers to your API
        """
        return pulumi.get(self, "forward_headers")

    @_builtins.property
    @pulumi.getter(name="notBefore")
    def not_before(self) -> pulumi.Output[Optional[_builtins.float]]:
        """
        Start time for Qstash Scheduling.
        """
        return pulumi.get(self, "not_before")

    @_builtins.property
    @pulumi.getter(name="qstashScheduleId")
    def qstash_schedule_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "qstash_schedule_id")

    @_builtins.property
    @pulumi.getter
    def retries(self) -> pulumi.Output[Optional[_builtins.float]]:
        """
        Retries for Qstash Schedule requests.
        """
        return pulumi.get(self, "retries")

    @_builtins.property
    @pulumi.getter(name="scheduleId")
    def schedule_id(self) -> pulumi.Output[_builtins.str]:
        """
        Unique Qstash Schedule ID for requested schedule
        """
        return pulumi.get(self, "schedule_id")

