# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['QstashEndpointArgs', 'QstashEndpoint']

@pulumi.input_type
class QstashEndpointArgs:
    def __init__(__self__, *,
                 topic_id: pulumi.Input[_builtins.str],
                 url: pulumi.Input[_builtins.str],
                 qstash_endpoint_id: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a QstashEndpoint resource.

        :param pulumi.Input[_builtins.str] topic_id: Topic Id that the endpoint is added to
        :param pulumi.Input[_builtins.str] url: URL of the endpoint
        """
        pulumi.set(__self__, "topic_id", topic_id)
        pulumi.set(__self__, "url", url)
        if qstash_endpoint_id is not None:
            pulumi.set(__self__, "qstash_endpoint_id", qstash_endpoint_id)

    @_builtins.property
    @pulumi.getter(name="topicId")
    def topic_id(self) -> pulumi.Input[_builtins.str]:
        """
        Topic Id that the endpoint is added to
        """
        return pulumi.get(self, "topic_id")

    @topic_id.setter
    def topic_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "topic_id", value)

    @_builtins.property
    @pulumi.getter
    def url(self) -> pulumi.Input[_builtins.str]:
        """
        URL of the endpoint
        """
        return pulumi.get(self, "url")

    @url.setter
    def url(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "url", value)

    @_builtins.property
    @pulumi.getter(name="qstashEndpointId")
    def qstash_endpoint_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "qstash_endpoint_id")

    @qstash_endpoint_id.setter
    def qstash_endpoint_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "qstash_endpoint_id", value)


@pulumi.input_type
class _QstashEndpointState:
    def __init__(__self__, *,
                 endpoint_id: pulumi.Input[Optional[_builtins.str]] = None,
                 qstash_endpoint_id: pulumi.Input[Optional[_builtins.str]] = None,
                 topic_id: pulumi.Input[Optional[_builtins.str]] = None,
                 topic_name: pulumi.Input[Optional[_builtins.str]] = None,
                 url: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering QstashEndpoint resources.

        :param pulumi.Input[_builtins.str] endpoint_id: Unique Qstash Endpoint ID
        :param pulumi.Input[_builtins.str] topic_id: Topic Id that the endpoint is added to
        :param pulumi.Input[_builtins.str] topic_name: Unique Qstash Topic Name for Endpoint
        :param pulumi.Input[_builtins.str] url: URL of the endpoint
        """
        if endpoint_id is not None:
            pulumi.set(__self__, "endpoint_id", endpoint_id)
        if qstash_endpoint_id is not None:
            pulumi.set(__self__, "qstash_endpoint_id", qstash_endpoint_id)
        if topic_id is not None:
            pulumi.set(__self__, "topic_id", topic_id)
        if topic_name is not None:
            pulumi.set(__self__, "topic_name", topic_name)
        if url is not None:
            pulumi.set(__self__, "url", url)

    @_builtins.property
    @pulumi.getter(name="endpointId")
    def endpoint_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Unique Qstash Endpoint ID
        """
        return pulumi.get(self, "endpoint_id")

    @endpoint_id.setter
    def endpoint_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "endpoint_id", value)

    @_builtins.property
    @pulumi.getter(name="qstashEndpointId")
    def qstash_endpoint_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "qstash_endpoint_id")

    @qstash_endpoint_id.setter
    def qstash_endpoint_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "qstash_endpoint_id", value)

    @_builtins.property
    @pulumi.getter(name="topicId")
    def topic_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Topic Id that the endpoint is added to
        """
        return pulumi.get(self, "topic_id")

    @topic_id.setter
    def topic_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "topic_id", value)

    @_builtins.property
    @pulumi.getter(name="topicName")
    def topic_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Unique Qstash Topic Name for Endpoint
        """
        return pulumi.get(self, "topic_name")

    @topic_name.setter
    def topic_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "topic_name", value)

    @_builtins.property
    @pulumi.getter
    def url(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        URL of the endpoint
        """
        return pulumi.get(self, "url")

    @url.setter
    def url(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "url", value)


@pulumi.type_token("upstash:index/qstashEndpoint:QstashEndpoint")
class QstashEndpoint(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 qstash_endpoint_id: pulumi.Input[Optional[_builtins.str]] = None,
                 topic_id: pulumi.Input[Optional[_builtins.str]] = None,
                 url: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Create a QstashEndpoint resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] topic_id: Topic Id that the endpoint is added to
        :param pulumi.Input[_builtins.str] url: URL of the endpoint
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: QstashEndpointArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a QstashEndpoint resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param QstashEndpointArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(QstashEndpointArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 qstash_endpoint_id: pulumi.Input[Optional[_builtins.str]] = None,
                 topic_id: pulumi.Input[Optional[_builtins.str]] = None,
                 url: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = QstashEndpointArgs.__new__(QstashEndpointArgs)

            __props__.__dict__["qstash_endpoint_id"] = qstash_endpoint_id
            if topic_id is None and not opts.urn:
                raise TypeError("Missing required property 'topic_id'")
            __props__.__dict__["topic_id"] = topic_id
            if url is None and not opts.urn:
                raise TypeError("Missing required property 'url'")
            __props__.__dict__["url"] = url
            __props__.__dict__["endpoint_id"] = None
            __props__.__dict__["topic_name"] = None
        super(QstashEndpoint, __self__).__init__(
            'upstash:index/qstashEndpoint:QstashEndpoint',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            endpoint_id: pulumi.Input[Optional[_builtins.str]] = None,
            qstash_endpoint_id: pulumi.Input[Optional[_builtins.str]] = None,
            topic_id: pulumi.Input[Optional[_builtins.str]] = None,
            topic_name: pulumi.Input[Optional[_builtins.str]] = None,
            url: pulumi.Input[Optional[_builtins.str]] = None) -> 'QstashEndpoint':
        """
        Get an existing QstashEndpoint resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] endpoint_id: Unique Qstash Endpoint ID
        :param pulumi.Input[_builtins.str] topic_id: Topic Id that the endpoint is added to
        :param pulumi.Input[_builtins.str] topic_name: Unique Qstash Topic Name for Endpoint
        :param pulumi.Input[_builtins.str] url: URL of the endpoint
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _QstashEndpointState.__new__(_QstashEndpointState)

        __props__.__dict__["endpoint_id"] = endpoint_id
        __props__.__dict__["qstash_endpoint_id"] = qstash_endpoint_id
        __props__.__dict__["topic_id"] = topic_id
        __props__.__dict__["topic_name"] = topic_name
        __props__.__dict__["url"] = url
        return QstashEndpoint(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="endpointId")
    def endpoint_id(self) -> pulumi.Output[_builtins.str]:
        """
        Unique Qstash Endpoint ID
        """
        return pulumi.get(self, "endpoint_id")

    @_builtins.property
    @pulumi.getter(name="qstashEndpointId")
    def qstash_endpoint_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "qstash_endpoint_id")

    @_builtins.property
    @pulumi.getter(name="topicId")
    def topic_id(self) -> pulumi.Output[_builtins.str]:
        """
        Topic Id that the endpoint is added to
        """
        return pulumi.get(self, "topic_id")

    @_builtins.property
    @pulumi.getter(name="topicName")
    def topic_name(self) -> pulumi.Output[_builtins.str]:
        """
        Unique Qstash Topic Name for Endpoint
        """
        return pulumi.get(self, "topic_name")

    @_builtins.property
    @pulumi.getter
    def url(self) -> pulumi.Output[_builtins.str]:
        """
        URL of the endpoint
        """
        return pulumi.get(self, "url")

