# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['RedisDatabaseArgs', 'RedisDatabase']

@pulumi.input_type
class RedisDatabaseArgs:
    def __init__(__self__, *,
                 database_name: pulumi.Input[_builtins.str],
                 region: pulumi.Input[_builtins.str],
                 auto_scale: pulumi.Input[Optional[_builtins.bool]] = None,
                 budget: pulumi.Input[Optional[_builtins.float]] = None,
                 consistent: pulumi.Input[Optional[_builtins.bool]] = None,
                 eviction: pulumi.Input[Optional[_builtins.bool]] = None,
                 ip_allowlists: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 multizone: pulumi.Input[Optional[_builtins.bool]] = None,
                 primary_region: pulumi.Input[Optional[_builtins.str]] = None,
                 prod_pack: pulumi.Input[Optional[_builtins.bool]] = None,
                 read_regions: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 redis_database_id: pulumi.Input[Optional[_builtins.str]] = None,
                 tls: pulumi.Input[Optional[_builtins.bool]] = None):
        """
        The set of arguments for constructing a RedisDatabase resource.

        :param pulumi.Input[_builtins.str] database_name: Name of the database
        :param pulumi.Input[_builtins.str] region: Region of the database. For global gcp regions, use `gcp-global`. For globals, check for<span pulumi-lang-nodejs=" primaryRegion " pulumi-lang-dotnet=" PrimaryRegion " pulumi-lang-go=" primaryRegion " pulumi-lang-python=" primary_region " pulumi-lang-yaml=" primaryRegion " pulumi-lang-java=" primaryRegion " pulumi-lang-hcl=" primary_region "> primaryRegion </span>and<span pulumi-lang-nodejs=" readRegions " pulumi-lang-dotnet=" ReadRegions " pulumi-lang-go=" readRegions " pulumi-lang-python=" read_regions " pulumi-lang-yaml=" readRegions " pulumi-lang-java=" readRegions " pulumi-lang-hcl=" read_regions "> readRegions </span>fields
        :param pulumi.Input[_builtins.bool] auto_scale: Upgrade to higher plans automatically when it hits quotas
        :param pulumi.Input[_builtins.float] budget: Budget for the database (default $20). It is used to limit the cost of the database. If the budget is reached, the database will be throttled until the next month.
        :param pulumi.Input[_builtins.bool] consistent: When enabled, all writes are synchronously persisted to the disk.
        :param pulumi.Input[_builtins.bool] eviction: Enable eviction, to evict keys when your database reaches the max size
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] ip_allowlists: Ip CIDR allowlist for the database. If not set, all IPs are allowed to connect to the database.
        :param pulumi.Input[_builtins.bool] multizone: When enabled, database becomes highly available and is deployed in multiple zones. (If changed to false from true, results in deletion and recreation of the resource)
        :param pulumi.Input[_builtins.str] primary_region: Primary region for the database (Only works if region='global'. Can be one of [us-east-1, us-west-1, us-west-2, eu-central-1, eu-west-1, sa-east-1, ap-southeast-1, ap-southeast-2])
        :param pulumi.Input[_builtins.bool] prod_pack: Whether Prod Pack is enabled for the database.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] read_regions: Read regions for the database (Only works if region='global' and<span pulumi-lang-nodejs=" primaryRegion " pulumi-lang-dotnet=" PrimaryRegion " pulumi-lang-go=" primaryRegion " pulumi-lang-python=" primary_region " pulumi-lang-yaml=" primaryRegion " pulumi-lang-java=" primaryRegion " pulumi-lang-hcl=" primary_region "> primaryRegion </span>is set. Can be any combination of [us-east-1, us-west-1, us-west-2, eu-central-1, eu-west-1, sa-east-1, ap-southeast-1, ap-southeast-2], excluding the one given as primary.)
        :param pulumi.Input[_builtins.bool] tls: When enabled, data is encrypted in transit. TLS is enabled by default for newly created databases and cannot be disabled.
        """
        pulumi.set(__self__, "database_name", database_name)
        pulumi.set(__self__, "region", region)
        if auto_scale is not None:
            pulumi.set(__self__, "auto_scale", auto_scale)
        if budget is not None:
            pulumi.set(__self__, "budget", budget)
        if consistent is not None:
            warnings.warn("""Deprecated""", DeprecationWarning)
            pulumi.log.warn("""consistent is deprecated: Deprecated""")
        if consistent is not None:
            pulumi.set(__self__, "consistent", consistent)
        if eviction is not None:
            pulumi.set(__self__, "eviction", eviction)
        if ip_allowlists is not None:
            pulumi.set(__self__, "ip_allowlists", ip_allowlists)
        if multizone is not None:
            warnings.warn("""Deprecated""", DeprecationWarning)
            pulumi.log.warn("""multizone is deprecated: Deprecated""")
        if multizone is not None:
            pulumi.set(__self__, "multizone", multizone)
        if primary_region is not None:
            pulumi.set(__self__, "primary_region", primary_region)
        if prod_pack is not None:
            pulumi.set(__self__, "prod_pack", prod_pack)
        if read_regions is not None:
            pulumi.set(__self__, "read_regions", read_regions)
        if redis_database_id is not None:
            pulumi.set(__self__, "redis_database_id", redis_database_id)
        if tls is not None:
            pulumi.set(__self__, "tls", tls)

    @_builtins.property
    @pulumi.getter(name="databaseName")
    def database_name(self) -> pulumi.Input[_builtins.str]:
        """
        Name of the database
        """
        return pulumi.get(self, "database_name")

    @database_name.setter
    def database_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "database_name", value)

    @_builtins.property
    @pulumi.getter
    def region(self) -> pulumi.Input[_builtins.str]:
        """
        Region of the database. For global gcp regions, use `gcp-global`. For globals, check for<span pulumi-lang-nodejs=" primaryRegion " pulumi-lang-dotnet=" PrimaryRegion " pulumi-lang-go=" primaryRegion " pulumi-lang-python=" primary_region " pulumi-lang-yaml=" primaryRegion " pulumi-lang-java=" primaryRegion " pulumi-lang-hcl=" primary_region "> primaryRegion </span>and<span pulumi-lang-nodejs=" readRegions " pulumi-lang-dotnet=" ReadRegions " pulumi-lang-go=" readRegions " pulumi-lang-python=" read_regions " pulumi-lang-yaml=" readRegions " pulumi-lang-java=" readRegions " pulumi-lang-hcl=" read_regions "> readRegions </span>fields
        """
        return pulumi.get(self, "region")

    @region.setter
    def region(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "region", value)

    @_builtins.property
    @pulumi.getter(name="autoScale")
    def auto_scale(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Upgrade to higher plans automatically when it hits quotas
        """
        return pulumi.get(self, "auto_scale")

    @auto_scale.setter
    def auto_scale(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "auto_scale", value)

    @_builtins.property
    @pulumi.getter
    def budget(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Budget for the database (default $20). It is used to limit the cost of the database. If the budget is reached, the database will be throttled until the next month.
        """
        return pulumi.get(self, "budget")

    @budget.setter
    def budget(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "budget", value)

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""Deprecated""")
    def consistent(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        When enabled, all writes are synchronously persisted to the disk.
        """
        return pulumi.get(self, "consistent")

    @consistent.setter
    def consistent(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "consistent", value)

    @_builtins.property
    @pulumi.getter
    def eviction(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Enable eviction, to evict keys when your database reaches the max size
        """
        return pulumi.get(self, "eviction")

    @eviction.setter
    def eviction(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "eviction", value)

    @_builtins.property
    @pulumi.getter(name="ipAllowlists")
    def ip_allowlists(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Ip CIDR allowlist for the database. If not set, all IPs are allowed to connect to the database.
        """
        return pulumi.get(self, "ip_allowlists")

    @ip_allowlists.setter
    def ip_allowlists(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "ip_allowlists", value)

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""Deprecated""")
    def multizone(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        When enabled, database becomes highly available and is deployed in multiple zones. (If changed to false from true, results in deletion and recreation of the resource)
        """
        return pulumi.get(self, "multizone")

    @multizone.setter
    def multizone(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "multizone", value)

    @_builtins.property
    @pulumi.getter(name="primaryRegion")
    def primary_region(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Primary region for the database (Only works if region='global'. Can be one of [us-east-1, us-west-1, us-west-2, eu-central-1, eu-west-1, sa-east-1, ap-southeast-1, ap-southeast-2])
        """
        return pulumi.get(self, "primary_region")

    @primary_region.setter
    def primary_region(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "primary_region", value)

    @_builtins.property
    @pulumi.getter(name="prodPack")
    def prod_pack(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether Prod Pack is enabled for the database.
        """
        return pulumi.get(self, "prod_pack")

    @prod_pack.setter
    def prod_pack(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "prod_pack", value)

    @_builtins.property
    @pulumi.getter(name="readRegions")
    def read_regions(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Read regions for the database (Only works if region='global' and<span pulumi-lang-nodejs=" primaryRegion " pulumi-lang-dotnet=" PrimaryRegion " pulumi-lang-go=" primaryRegion " pulumi-lang-python=" primary_region " pulumi-lang-yaml=" primaryRegion " pulumi-lang-java=" primaryRegion " pulumi-lang-hcl=" primary_region "> primaryRegion </span>is set. Can be any combination of [us-east-1, us-west-1, us-west-2, eu-central-1, eu-west-1, sa-east-1, ap-southeast-1, ap-southeast-2], excluding the one given as primary.)
        """
        return pulumi.get(self, "read_regions")

    @read_regions.setter
    def read_regions(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "read_regions", value)

    @_builtins.property
    @pulumi.getter(name="redisDatabaseId")
    def redis_database_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "redis_database_id")

    @redis_database_id.setter
    def redis_database_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "redis_database_id", value)

    @_builtins.property
    @pulumi.getter
    def tls(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        When enabled, data is encrypted in transit. TLS is enabled by default for newly created databases and cannot be disabled.
        """
        return pulumi.get(self, "tls")

    @tls.setter
    def tls(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "tls", value)


@pulumi.input_type
class _RedisDatabaseState:
    def __init__(__self__, *,
                 auto_scale: pulumi.Input[Optional[_builtins.bool]] = None,
                 budget: pulumi.Input[Optional[_builtins.float]] = None,
                 consistent: pulumi.Input[Optional[_builtins.bool]] = None,
                 creation_time: pulumi.Input[Optional[_builtins.float]] = None,
                 database_id: pulumi.Input[Optional[_builtins.str]] = None,
                 database_name: pulumi.Input[Optional[_builtins.str]] = None,
                 database_type: pulumi.Input[Optional[_builtins.str]] = None,
                 db_daily_bandwidth_limit: pulumi.Input[Optional[_builtins.float]] = None,
                 db_disk_threshold: pulumi.Input[Optional[_builtins.float]] = None,
                 db_max_clients: pulumi.Input[Optional[_builtins.float]] = None,
                 db_max_commands_per_second: pulumi.Input[Optional[_builtins.float]] = None,
                 db_max_entry_size: pulumi.Input[Optional[_builtins.float]] = None,
                 db_max_request_size: pulumi.Input[Optional[_builtins.float]] = None,
                 db_memory_threshold: pulumi.Input[Optional[_builtins.float]] = None,
                 endpoint: pulumi.Input[Optional[_builtins.str]] = None,
                 eviction: pulumi.Input[Optional[_builtins.bool]] = None,
                 ip_allowlists: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 multizone: pulumi.Input[Optional[_builtins.bool]] = None,
                 password: pulumi.Input[Optional[_builtins.str]] = None,
                 port: pulumi.Input[Optional[_builtins.float]] = None,
                 primary_region: pulumi.Input[Optional[_builtins.str]] = None,
                 prod_pack: pulumi.Input[Optional[_builtins.bool]] = None,
                 read_only_rest_token: pulumi.Input[Optional[_builtins.str]] = None,
                 read_regions: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 redis_database_id: pulumi.Input[Optional[_builtins.str]] = None,
                 region: pulumi.Input[Optional[_builtins.str]] = None,
                 rest_token: pulumi.Input[Optional[_builtins.str]] = None,
                 state: pulumi.Input[Optional[_builtins.str]] = None,
                 tls: pulumi.Input[Optional[_builtins.bool]] = None,
                 user_email: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering RedisDatabase resources.

        :param pulumi.Input[_builtins.bool] auto_scale: Upgrade to higher plans automatically when it hits quotas
        :param pulumi.Input[_builtins.float] budget: Budget for the database (default $20). It is used to limit the cost of the database. If the budget is reached, the database will be throttled until the next month.
        :param pulumi.Input[_builtins.bool] consistent: When enabled, all writes are synchronously persisted to the disk.
        :param pulumi.Input[_builtins.float] creation_time: Creation time of the database
        :param pulumi.Input[_builtins.str] database_id: Unique Database ID for created database
        :param pulumi.Input[_builtins.str] database_name: Name of the database
        :param pulumi.Input[_builtins.str] database_type: Type of the database
        :param pulumi.Input[_builtins.float] db_daily_bandwidth_limit: Daily bandwidth limit for the database
        :param pulumi.Input[_builtins.float] db_disk_threshold: Disk threshold for the database
        :param pulumi.Input[_builtins.float] db_max_clients: Max clients for the database
        :param pulumi.Input[_builtins.float] db_max_commands_per_second: Max commands per second for the database
        :param pulumi.Input[_builtins.float] db_max_entry_size: Max entry size for the database
        :param pulumi.Input[_builtins.float] db_max_request_size: Max request size for the database
        :param pulumi.Input[_builtins.float] db_memory_threshold: Memory threshold for the database
        :param pulumi.Input[_builtins.str] endpoint: Database URL for connection
        :param pulumi.Input[_builtins.bool] eviction: Enable eviction, to evict keys when your database reaches the max size
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] ip_allowlists: Ip CIDR allowlist for the database. If not set, all IPs are allowed to connect to the database.
        :param pulumi.Input[_builtins.bool] multizone: When enabled, database becomes highly available and is deployed in multiple zones. (If changed to false from true, results in deletion and recreation of the resource)
        :param pulumi.Input[_builtins.str] password: Password of the database
        :param pulumi.Input[_builtins.float] port: Port of the endpoint
        :param pulumi.Input[_builtins.str] primary_region: Primary region for the database (Only works if region='global'. Can be one of [us-east-1, us-west-1, us-west-2, eu-central-1, eu-west-1, sa-east-1, ap-southeast-1, ap-southeast-2])
        :param pulumi.Input[_builtins.bool] prod_pack: Whether Prod Pack is enabled for the database.
        :param pulumi.Input[_builtins.str] read_only_rest_token: Rest Token for the database.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] read_regions: Read regions for the database (Only works if region='global' and<span pulumi-lang-nodejs=" primaryRegion " pulumi-lang-dotnet=" PrimaryRegion " pulumi-lang-go=" primaryRegion " pulumi-lang-python=" primary_region " pulumi-lang-yaml=" primaryRegion " pulumi-lang-java=" primaryRegion " pulumi-lang-hcl=" primary_region "> primaryRegion </span>is set. Can be any combination of [us-east-1, us-west-1, us-west-2, eu-central-1, eu-west-1, sa-east-1, ap-southeast-1, ap-southeast-2], excluding the one given as primary.)
        :param pulumi.Input[_builtins.str] region: Region of the database. For global gcp regions, use `gcp-global`. For globals, check for<span pulumi-lang-nodejs=" primaryRegion " pulumi-lang-dotnet=" PrimaryRegion " pulumi-lang-go=" primaryRegion " pulumi-lang-python=" primary_region " pulumi-lang-yaml=" primaryRegion " pulumi-lang-java=" primaryRegion " pulumi-lang-hcl=" primary_region "> primaryRegion </span>and<span pulumi-lang-nodejs=" readRegions " pulumi-lang-dotnet=" ReadRegions " pulumi-lang-go=" readRegions " pulumi-lang-python=" read_regions " pulumi-lang-yaml=" readRegions " pulumi-lang-java=" readRegions " pulumi-lang-hcl=" read_regions "> readRegions </span>fields
        :param pulumi.Input[_builtins.str] rest_token: Rest Token for the database.
        :param pulumi.Input[_builtins.str] state: State of the database
        :param pulumi.Input[_builtins.bool] tls: When enabled, data is encrypted in transit. TLS is enabled by default for newly created databases and cannot be disabled.
        :param pulumi.Input[_builtins.str] user_email: User email for the database
        """
        if auto_scale is not None:
            pulumi.set(__self__, "auto_scale", auto_scale)
        if budget is not None:
            pulumi.set(__self__, "budget", budget)
        if consistent is not None:
            warnings.warn("""Deprecated""", DeprecationWarning)
            pulumi.log.warn("""consistent is deprecated: Deprecated""")
        if consistent is not None:
            pulumi.set(__self__, "consistent", consistent)
        if creation_time is not None:
            pulumi.set(__self__, "creation_time", creation_time)
        if database_id is not None:
            pulumi.set(__self__, "database_id", database_id)
        if database_name is not None:
            pulumi.set(__self__, "database_name", database_name)
        if database_type is not None:
            pulumi.set(__self__, "database_type", database_type)
        if db_daily_bandwidth_limit is not None:
            pulumi.set(__self__, "db_daily_bandwidth_limit", db_daily_bandwidth_limit)
        if db_disk_threshold is not None:
            pulumi.set(__self__, "db_disk_threshold", db_disk_threshold)
        if db_max_clients is not None:
            pulumi.set(__self__, "db_max_clients", db_max_clients)
        if db_max_commands_per_second is not None:
            pulumi.set(__self__, "db_max_commands_per_second", db_max_commands_per_second)
        if db_max_entry_size is not None:
            pulumi.set(__self__, "db_max_entry_size", db_max_entry_size)
        if db_max_request_size is not None:
            pulumi.set(__self__, "db_max_request_size", db_max_request_size)
        if db_memory_threshold is not None:
            pulumi.set(__self__, "db_memory_threshold", db_memory_threshold)
        if endpoint is not None:
            pulumi.set(__self__, "endpoint", endpoint)
        if eviction is not None:
            pulumi.set(__self__, "eviction", eviction)
        if ip_allowlists is not None:
            pulumi.set(__self__, "ip_allowlists", ip_allowlists)
        if multizone is not None:
            warnings.warn("""Deprecated""", DeprecationWarning)
            pulumi.log.warn("""multizone is deprecated: Deprecated""")
        if multizone is not None:
            pulumi.set(__self__, "multizone", multizone)
        if password is not None:
            pulumi.set(__self__, "password", password)
        if port is not None:
            pulumi.set(__self__, "port", port)
        if primary_region is not None:
            pulumi.set(__self__, "primary_region", primary_region)
        if prod_pack is not None:
            pulumi.set(__self__, "prod_pack", prod_pack)
        if read_only_rest_token is not None:
            pulumi.set(__self__, "read_only_rest_token", read_only_rest_token)
        if read_regions is not None:
            pulumi.set(__self__, "read_regions", read_regions)
        if redis_database_id is not None:
            pulumi.set(__self__, "redis_database_id", redis_database_id)
        if region is not None:
            pulumi.set(__self__, "region", region)
        if rest_token is not None:
            pulumi.set(__self__, "rest_token", rest_token)
        if state is not None:
            pulumi.set(__self__, "state", state)
        if tls is not None:
            pulumi.set(__self__, "tls", tls)
        if user_email is not None:
            pulumi.set(__self__, "user_email", user_email)

    @_builtins.property
    @pulumi.getter(name="autoScale")
    def auto_scale(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Upgrade to higher plans automatically when it hits quotas
        """
        return pulumi.get(self, "auto_scale")

    @auto_scale.setter
    def auto_scale(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "auto_scale", value)

    @_builtins.property
    @pulumi.getter
    def budget(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Budget for the database (default $20). It is used to limit the cost of the database. If the budget is reached, the database will be throttled until the next month.
        """
        return pulumi.get(self, "budget")

    @budget.setter
    def budget(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "budget", value)

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""Deprecated""")
    def consistent(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        When enabled, all writes are synchronously persisted to the disk.
        """
        return pulumi.get(self, "consistent")

    @consistent.setter
    def consistent(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "consistent", value)

    @_builtins.property
    @pulumi.getter(name="creationTime")
    def creation_time(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Creation time of the database
        """
        return pulumi.get(self, "creation_time")

    @creation_time.setter
    def creation_time(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "creation_time", value)

    @_builtins.property
    @pulumi.getter(name="databaseId")
    def database_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Unique Database ID for created database
        """
        return pulumi.get(self, "database_id")

    @database_id.setter
    def database_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "database_id", value)

    @_builtins.property
    @pulumi.getter(name="databaseName")
    def database_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Name of the database
        """
        return pulumi.get(self, "database_name")

    @database_name.setter
    def database_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "database_name", value)

    @_builtins.property
    @pulumi.getter(name="databaseType")
    def database_type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Type of the database
        """
        return pulumi.get(self, "database_type")

    @database_type.setter
    def database_type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "database_type", value)

    @_builtins.property
    @pulumi.getter(name="dbDailyBandwidthLimit")
    def db_daily_bandwidth_limit(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Daily bandwidth limit for the database
        """
        return pulumi.get(self, "db_daily_bandwidth_limit")

    @db_daily_bandwidth_limit.setter
    def db_daily_bandwidth_limit(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "db_daily_bandwidth_limit", value)

    @_builtins.property
    @pulumi.getter(name="dbDiskThreshold")
    def db_disk_threshold(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Disk threshold for the database
        """
        return pulumi.get(self, "db_disk_threshold")

    @db_disk_threshold.setter
    def db_disk_threshold(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "db_disk_threshold", value)

    @_builtins.property
    @pulumi.getter(name="dbMaxClients")
    def db_max_clients(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Max clients for the database
        """
        return pulumi.get(self, "db_max_clients")

    @db_max_clients.setter
    def db_max_clients(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "db_max_clients", value)

    @_builtins.property
    @pulumi.getter(name="dbMaxCommandsPerSecond")
    def db_max_commands_per_second(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Max commands per second for the database
        """
        return pulumi.get(self, "db_max_commands_per_second")

    @db_max_commands_per_second.setter
    def db_max_commands_per_second(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "db_max_commands_per_second", value)

    @_builtins.property
    @pulumi.getter(name="dbMaxEntrySize")
    def db_max_entry_size(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Max entry size for the database
        """
        return pulumi.get(self, "db_max_entry_size")

    @db_max_entry_size.setter
    def db_max_entry_size(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "db_max_entry_size", value)

    @_builtins.property
    @pulumi.getter(name="dbMaxRequestSize")
    def db_max_request_size(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Max request size for the database
        """
        return pulumi.get(self, "db_max_request_size")

    @db_max_request_size.setter
    def db_max_request_size(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "db_max_request_size", value)

    @_builtins.property
    @pulumi.getter(name="dbMemoryThreshold")
    def db_memory_threshold(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Memory threshold for the database
        """
        return pulumi.get(self, "db_memory_threshold")

    @db_memory_threshold.setter
    def db_memory_threshold(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "db_memory_threshold", value)

    @_builtins.property
    @pulumi.getter
    def endpoint(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Database URL for connection
        """
        return pulumi.get(self, "endpoint")

    @endpoint.setter
    def endpoint(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "endpoint", value)

    @_builtins.property
    @pulumi.getter
    def eviction(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Enable eviction, to evict keys when your database reaches the max size
        """
        return pulumi.get(self, "eviction")

    @eviction.setter
    def eviction(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "eviction", value)

    @_builtins.property
    @pulumi.getter(name="ipAllowlists")
    def ip_allowlists(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Ip CIDR allowlist for the database. If not set, all IPs are allowed to connect to the database.
        """
        return pulumi.get(self, "ip_allowlists")

    @ip_allowlists.setter
    def ip_allowlists(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "ip_allowlists", value)

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""Deprecated""")
    def multizone(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        When enabled, database becomes highly available and is deployed in multiple zones. (If changed to false from true, results in deletion and recreation of the resource)
        """
        return pulumi.get(self, "multizone")

    @multizone.setter
    def multizone(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "multizone", value)

    @_builtins.property
    @pulumi.getter
    def password(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Password of the database
        """
        return pulumi.get(self, "password")

    @password.setter
    def password(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "password", value)

    @_builtins.property
    @pulumi.getter
    def port(self) -> pulumi.Input[Optional[_builtins.float]]:
        """
        Port of the endpoint
        """
        return pulumi.get(self, "port")

    @port.setter
    def port(self, value: pulumi.Input[Optional[_builtins.float]]):
        pulumi.set(self, "port", value)

    @_builtins.property
    @pulumi.getter(name="primaryRegion")
    def primary_region(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Primary region for the database (Only works if region='global'. Can be one of [us-east-1, us-west-1, us-west-2, eu-central-1, eu-west-1, sa-east-1, ap-southeast-1, ap-southeast-2])
        """
        return pulumi.get(self, "primary_region")

    @primary_region.setter
    def primary_region(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "primary_region", value)

    @_builtins.property
    @pulumi.getter(name="prodPack")
    def prod_pack(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether Prod Pack is enabled for the database.
        """
        return pulumi.get(self, "prod_pack")

    @prod_pack.setter
    def prod_pack(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "prod_pack", value)

    @_builtins.property
    @pulumi.getter(name="readOnlyRestToken")
    def read_only_rest_token(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Rest Token for the database.
        """
        return pulumi.get(self, "read_only_rest_token")

    @read_only_rest_token.setter
    def read_only_rest_token(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "read_only_rest_token", value)

    @_builtins.property
    @pulumi.getter(name="readRegions")
    def read_regions(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Read regions for the database (Only works if region='global' and<span pulumi-lang-nodejs=" primaryRegion " pulumi-lang-dotnet=" PrimaryRegion " pulumi-lang-go=" primaryRegion " pulumi-lang-python=" primary_region " pulumi-lang-yaml=" primaryRegion " pulumi-lang-java=" primaryRegion " pulumi-lang-hcl=" primary_region "> primaryRegion </span>is set. Can be any combination of [us-east-1, us-west-1, us-west-2, eu-central-1, eu-west-1, sa-east-1, ap-southeast-1, ap-southeast-2], excluding the one given as primary.)
        """
        return pulumi.get(self, "read_regions")

    @read_regions.setter
    def read_regions(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "read_regions", value)

    @_builtins.property
    @pulumi.getter(name="redisDatabaseId")
    def redis_database_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "redis_database_id")

    @redis_database_id.setter
    def redis_database_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "redis_database_id", value)

    @_builtins.property
    @pulumi.getter
    def region(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Region of the database. For global gcp regions, use `gcp-global`. For globals, check for<span pulumi-lang-nodejs=" primaryRegion " pulumi-lang-dotnet=" PrimaryRegion " pulumi-lang-go=" primaryRegion " pulumi-lang-python=" primary_region " pulumi-lang-yaml=" primaryRegion " pulumi-lang-java=" primaryRegion " pulumi-lang-hcl=" primary_region "> primaryRegion </span>and<span pulumi-lang-nodejs=" readRegions " pulumi-lang-dotnet=" ReadRegions " pulumi-lang-go=" readRegions " pulumi-lang-python=" read_regions " pulumi-lang-yaml=" readRegions " pulumi-lang-java=" readRegions " pulumi-lang-hcl=" read_regions "> readRegions </span>fields
        """
        return pulumi.get(self, "region")

    @region.setter
    def region(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "region", value)

    @_builtins.property
    @pulumi.getter(name="restToken")
    def rest_token(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Rest Token for the database.
        """
        return pulumi.get(self, "rest_token")

    @rest_token.setter
    def rest_token(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "rest_token", value)

    @_builtins.property
    @pulumi.getter
    def state(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        State of the database
        """
        return pulumi.get(self, "state")

    @state.setter
    def state(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "state", value)

    @_builtins.property
    @pulumi.getter
    def tls(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        When enabled, data is encrypted in transit. TLS is enabled by default for newly created databases and cannot be disabled.
        """
        return pulumi.get(self, "tls")

    @tls.setter
    def tls(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "tls", value)

    @_builtins.property
    @pulumi.getter(name="userEmail")
    def user_email(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        User email for the database
        """
        return pulumi.get(self, "user_email")

    @user_email.setter
    def user_email(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "user_email", value)


@pulumi.type_token("upstash:index/redisDatabase:RedisDatabase")
class RedisDatabase(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 auto_scale: pulumi.Input[Optional[_builtins.bool]] = None,
                 budget: pulumi.Input[Optional[_builtins.float]] = None,
                 consistent: pulumi.Input[Optional[_builtins.bool]] = None,
                 database_name: pulumi.Input[Optional[_builtins.str]] = None,
                 eviction: pulumi.Input[Optional[_builtins.bool]] = None,
                 ip_allowlists: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 multizone: pulumi.Input[Optional[_builtins.bool]] = None,
                 primary_region: pulumi.Input[Optional[_builtins.str]] = None,
                 prod_pack: pulumi.Input[Optional[_builtins.bool]] = None,
                 read_regions: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 redis_database_id: pulumi.Input[Optional[_builtins.str]] = None,
                 region: pulumi.Input[Optional[_builtins.str]] = None,
                 tls: pulumi.Input[Optional[_builtins.bool]] = None,
                 __props__=None):
        """
        Create a RedisDatabase resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] auto_scale: Upgrade to higher plans automatically when it hits quotas
        :param pulumi.Input[_builtins.float] budget: Budget for the database (default $20). It is used to limit the cost of the database. If the budget is reached, the database will be throttled until the next month.
        :param pulumi.Input[_builtins.bool] consistent: When enabled, all writes are synchronously persisted to the disk.
        :param pulumi.Input[_builtins.str] database_name: Name of the database
        :param pulumi.Input[_builtins.bool] eviction: Enable eviction, to evict keys when your database reaches the max size
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] ip_allowlists: Ip CIDR allowlist for the database. If not set, all IPs are allowed to connect to the database.
        :param pulumi.Input[_builtins.bool] multizone: When enabled, database becomes highly available and is deployed in multiple zones. (If changed to false from true, results in deletion and recreation of the resource)
        :param pulumi.Input[_builtins.str] primary_region: Primary region for the database (Only works if region='global'. Can be one of [us-east-1, us-west-1, us-west-2, eu-central-1, eu-west-1, sa-east-1, ap-southeast-1, ap-southeast-2])
        :param pulumi.Input[_builtins.bool] prod_pack: Whether Prod Pack is enabled for the database.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] read_regions: Read regions for the database (Only works if region='global' and<span pulumi-lang-nodejs=" primaryRegion " pulumi-lang-dotnet=" PrimaryRegion " pulumi-lang-go=" primaryRegion " pulumi-lang-python=" primary_region " pulumi-lang-yaml=" primaryRegion " pulumi-lang-java=" primaryRegion " pulumi-lang-hcl=" primary_region "> primaryRegion </span>is set. Can be any combination of [us-east-1, us-west-1, us-west-2, eu-central-1, eu-west-1, sa-east-1, ap-southeast-1, ap-southeast-2], excluding the one given as primary.)
        :param pulumi.Input[_builtins.str] region: Region of the database. For global gcp regions, use `gcp-global`. For globals, check for<span pulumi-lang-nodejs=" primaryRegion " pulumi-lang-dotnet=" PrimaryRegion " pulumi-lang-go=" primaryRegion " pulumi-lang-python=" primary_region " pulumi-lang-yaml=" primaryRegion " pulumi-lang-java=" primaryRegion " pulumi-lang-hcl=" primary_region "> primaryRegion </span>and<span pulumi-lang-nodejs=" readRegions " pulumi-lang-dotnet=" ReadRegions " pulumi-lang-go=" readRegions " pulumi-lang-python=" read_regions " pulumi-lang-yaml=" readRegions " pulumi-lang-java=" readRegions " pulumi-lang-hcl=" read_regions "> readRegions </span>fields
        :param pulumi.Input[_builtins.bool] tls: When enabled, data is encrypted in transit. TLS is enabled by default for newly created databases and cannot be disabled.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: RedisDatabaseArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a RedisDatabase resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param RedisDatabaseArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(RedisDatabaseArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 auto_scale: pulumi.Input[Optional[_builtins.bool]] = None,
                 budget: pulumi.Input[Optional[_builtins.float]] = None,
                 consistent: pulumi.Input[Optional[_builtins.bool]] = None,
                 database_name: pulumi.Input[Optional[_builtins.str]] = None,
                 eviction: pulumi.Input[Optional[_builtins.bool]] = None,
                 ip_allowlists: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 multizone: pulumi.Input[Optional[_builtins.bool]] = None,
                 primary_region: pulumi.Input[Optional[_builtins.str]] = None,
                 prod_pack: pulumi.Input[Optional[_builtins.bool]] = None,
                 read_regions: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 redis_database_id: pulumi.Input[Optional[_builtins.str]] = None,
                 region: pulumi.Input[Optional[_builtins.str]] = None,
                 tls: pulumi.Input[Optional[_builtins.bool]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = RedisDatabaseArgs.__new__(RedisDatabaseArgs)

            __props__.__dict__["auto_scale"] = auto_scale
            __props__.__dict__["budget"] = budget
            __props__.__dict__["consistent"] = consistent
            if database_name is None and not opts.urn:
                raise TypeError("Missing required property 'database_name'")
            __props__.__dict__["database_name"] = database_name
            __props__.__dict__["eviction"] = eviction
            __props__.__dict__["ip_allowlists"] = ip_allowlists
            __props__.__dict__["multizone"] = multizone
            __props__.__dict__["primary_region"] = primary_region
            __props__.__dict__["prod_pack"] = prod_pack
            __props__.__dict__["read_regions"] = read_regions
            __props__.__dict__["redis_database_id"] = redis_database_id
            if region is None and not opts.urn:
                raise TypeError("Missing required property 'region'")
            __props__.__dict__["region"] = region
            __props__.__dict__["tls"] = tls
            __props__.__dict__["creation_time"] = None
            __props__.__dict__["database_id"] = None
            __props__.__dict__["database_type"] = None
            __props__.__dict__["db_daily_bandwidth_limit"] = None
            __props__.__dict__["db_disk_threshold"] = None
            __props__.__dict__["db_max_clients"] = None
            __props__.__dict__["db_max_commands_per_second"] = None
            __props__.__dict__["db_max_entry_size"] = None
            __props__.__dict__["db_max_request_size"] = None
            __props__.__dict__["db_memory_threshold"] = None
            __props__.__dict__["endpoint"] = None
            __props__.__dict__["password"] = None
            __props__.__dict__["port"] = None
            __props__.__dict__["read_only_rest_token"] = None
            __props__.__dict__["rest_token"] = None
            __props__.__dict__["state"] = None
            __props__.__dict__["user_email"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["password", "readOnlyRestToken", "restToken"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(RedisDatabase, __self__).__init__(
            'upstash:index/redisDatabase:RedisDatabase',
            resource_name,
            __props__,
            opts,
            package_ref=_utilities.get_package())

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            auto_scale: pulumi.Input[Optional[_builtins.bool]] = None,
            budget: pulumi.Input[Optional[_builtins.float]] = None,
            consistent: pulumi.Input[Optional[_builtins.bool]] = None,
            creation_time: pulumi.Input[Optional[_builtins.float]] = None,
            database_id: pulumi.Input[Optional[_builtins.str]] = None,
            database_name: pulumi.Input[Optional[_builtins.str]] = None,
            database_type: pulumi.Input[Optional[_builtins.str]] = None,
            db_daily_bandwidth_limit: pulumi.Input[Optional[_builtins.float]] = None,
            db_disk_threshold: pulumi.Input[Optional[_builtins.float]] = None,
            db_max_clients: pulumi.Input[Optional[_builtins.float]] = None,
            db_max_commands_per_second: pulumi.Input[Optional[_builtins.float]] = None,
            db_max_entry_size: pulumi.Input[Optional[_builtins.float]] = None,
            db_max_request_size: pulumi.Input[Optional[_builtins.float]] = None,
            db_memory_threshold: pulumi.Input[Optional[_builtins.float]] = None,
            endpoint: pulumi.Input[Optional[_builtins.str]] = None,
            eviction: pulumi.Input[Optional[_builtins.bool]] = None,
            ip_allowlists: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
            multizone: pulumi.Input[Optional[_builtins.bool]] = None,
            password: pulumi.Input[Optional[_builtins.str]] = None,
            port: pulumi.Input[Optional[_builtins.float]] = None,
            primary_region: pulumi.Input[Optional[_builtins.str]] = None,
            prod_pack: pulumi.Input[Optional[_builtins.bool]] = None,
            read_only_rest_token: pulumi.Input[Optional[_builtins.str]] = None,
            read_regions: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
            redis_database_id: pulumi.Input[Optional[_builtins.str]] = None,
            region: pulumi.Input[Optional[_builtins.str]] = None,
            rest_token: pulumi.Input[Optional[_builtins.str]] = None,
            state: pulumi.Input[Optional[_builtins.str]] = None,
            tls: pulumi.Input[Optional[_builtins.bool]] = None,
            user_email: pulumi.Input[Optional[_builtins.str]] = None) -> 'RedisDatabase':
        """
        Get an existing RedisDatabase resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] auto_scale: Upgrade to higher plans automatically when it hits quotas
        :param pulumi.Input[_builtins.float] budget: Budget for the database (default $20). It is used to limit the cost of the database. If the budget is reached, the database will be throttled until the next month.
        :param pulumi.Input[_builtins.bool] consistent: When enabled, all writes are synchronously persisted to the disk.
        :param pulumi.Input[_builtins.float] creation_time: Creation time of the database
        :param pulumi.Input[_builtins.str] database_id: Unique Database ID for created database
        :param pulumi.Input[_builtins.str] database_name: Name of the database
        :param pulumi.Input[_builtins.str] database_type: Type of the database
        :param pulumi.Input[_builtins.float] db_daily_bandwidth_limit: Daily bandwidth limit for the database
        :param pulumi.Input[_builtins.float] db_disk_threshold: Disk threshold for the database
        :param pulumi.Input[_builtins.float] db_max_clients: Max clients for the database
        :param pulumi.Input[_builtins.float] db_max_commands_per_second: Max commands per second for the database
        :param pulumi.Input[_builtins.float] db_max_entry_size: Max entry size for the database
        :param pulumi.Input[_builtins.float] db_max_request_size: Max request size for the database
        :param pulumi.Input[_builtins.float] db_memory_threshold: Memory threshold for the database
        :param pulumi.Input[_builtins.str] endpoint: Database URL for connection
        :param pulumi.Input[_builtins.bool] eviction: Enable eviction, to evict keys when your database reaches the max size
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] ip_allowlists: Ip CIDR allowlist for the database. If not set, all IPs are allowed to connect to the database.
        :param pulumi.Input[_builtins.bool] multizone: When enabled, database becomes highly available and is deployed in multiple zones. (If changed to false from true, results in deletion and recreation of the resource)
        :param pulumi.Input[_builtins.str] password: Password of the database
        :param pulumi.Input[_builtins.float] port: Port of the endpoint
        :param pulumi.Input[_builtins.str] primary_region: Primary region for the database (Only works if region='global'. Can be one of [us-east-1, us-west-1, us-west-2, eu-central-1, eu-west-1, sa-east-1, ap-southeast-1, ap-southeast-2])
        :param pulumi.Input[_builtins.bool] prod_pack: Whether Prod Pack is enabled for the database.
        :param pulumi.Input[_builtins.str] read_only_rest_token: Rest Token for the database.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] read_regions: Read regions for the database (Only works if region='global' and<span pulumi-lang-nodejs=" primaryRegion " pulumi-lang-dotnet=" PrimaryRegion " pulumi-lang-go=" primaryRegion " pulumi-lang-python=" primary_region " pulumi-lang-yaml=" primaryRegion " pulumi-lang-java=" primaryRegion " pulumi-lang-hcl=" primary_region "> primaryRegion </span>is set. Can be any combination of [us-east-1, us-west-1, us-west-2, eu-central-1, eu-west-1, sa-east-1, ap-southeast-1, ap-southeast-2], excluding the one given as primary.)
        :param pulumi.Input[_builtins.str] region: Region of the database. For global gcp regions, use `gcp-global`. For globals, check for<span pulumi-lang-nodejs=" primaryRegion " pulumi-lang-dotnet=" PrimaryRegion " pulumi-lang-go=" primaryRegion " pulumi-lang-python=" primary_region " pulumi-lang-yaml=" primaryRegion " pulumi-lang-java=" primaryRegion " pulumi-lang-hcl=" primary_region "> primaryRegion </span>and<span pulumi-lang-nodejs=" readRegions " pulumi-lang-dotnet=" ReadRegions " pulumi-lang-go=" readRegions " pulumi-lang-python=" read_regions " pulumi-lang-yaml=" readRegions " pulumi-lang-java=" readRegions " pulumi-lang-hcl=" read_regions "> readRegions </span>fields
        :param pulumi.Input[_builtins.str] rest_token: Rest Token for the database.
        :param pulumi.Input[_builtins.str] state: State of the database
        :param pulumi.Input[_builtins.bool] tls: When enabled, data is encrypted in transit. TLS is enabled by default for newly created databases and cannot be disabled.
        :param pulumi.Input[_builtins.str] user_email: User email for the database
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _RedisDatabaseState.__new__(_RedisDatabaseState)

        __props__.__dict__["auto_scale"] = auto_scale
        __props__.__dict__["budget"] = budget
        __props__.__dict__["consistent"] = consistent
        __props__.__dict__["creation_time"] = creation_time
        __props__.__dict__["database_id"] = database_id
        __props__.__dict__["database_name"] = database_name
        __props__.__dict__["database_type"] = database_type
        __props__.__dict__["db_daily_bandwidth_limit"] = db_daily_bandwidth_limit
        __props__.__dict__["db_disk_threshold"] = db_disk_threshold
        __props__.__dict__["db_max_clients"] = db_max_clients
        __props__.__dict__["db_max_commands_per_second"] = db_max_commands_per_second
        __props__.__dict__["db_max_entry_size"] = db_max_entry_size
        __props__.__dict__["db_max_request_size"] = db_max_request_size
        __props__.__dict__["db_memory_threshold"] = db_memory_threshold
        __props__.__dict__["endpoint"] = endpoint
        __props__.__dict__["eviction"] = eviction
        __props__.__dict__["ip_allowlists"] = ip_allowlists
        __props__.__dict__["multizone"] = multizone
        __props__.__dict__["password"] = password
        __props__.__dict__["port"] = port
        __props__.__dict__["primary_region"] = primary_region
        __props__.__dict__["prod_pack"] = prod_pack
        __props__.__dict__["read_only_rest_token"] = read_only_rest_token
        __props__.__dict__["read_regions"] = read_regions
        __props__.__dict__["redis_database_id"] = redis_database_id
        __props__.__dict__["region"] = region
        __props__.__dict__["rest_token"] = rest_token
        __props__.__dict__["state"] = state
        __props__.__dict__["tls"] = tls
        __props__.__dict__["user_email"] = user_email
        return RedisDatabase(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="autoScale")
    def auto_scale(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Upgrade to higher plans automatically when it hits quotas
        """
        return pulumi.get(self, "auto_scale")

    @_builtins.property
    @pulumi.getter
    def budget(self) -> pulumi.Output[Optional[_builtins.float]]:
        """
        Budget for the database (default $20). It is used to limit the cost of the database. If the budget is reached, the database will be throttled until the next month.
        """
        return pulumi.get(self, "budget")

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""Deprecated""")
    def consistent(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        When enabled, all writes are synchronously persisted to the disk.
        """
        return pulumi.get(self, "consistent")

    @_builtins.property
    @pulumi.getter(name="creationTime")
    def creation_time(self) -> pulumi.Output[_builtins.float]:
        """
        Creation time of the database
        """
        return pulumi.get(self, "creation_time")

    @_builtins.property
    @pulumi.getter(name="databaseId")
    def database_id(self) -> pulumi.Output[_builtins.str]:
        """
        Unique Database ID for created database
        """
        return pulumi.get(self, "database_id")

    @_builtins.property
    @pulumi.getter(name="databaseName")
    def database_name(self) -> pulumi.Output[_builtins.str]:
        """
        Name of the database
        """
        return pulumi.get(self, "database_name")

    @_builtins.property
    @pulumi.getter(name="databaseType")
    def database_type(self) -> pulumi.Output[_builtins.str]:
        """
        Type of the database
        """
        return pulumi.get(self, "database_type")

    @_builtins.property
    @pulumi.getter(name="dbDailyBandwidthLimit")
    def db_daily_bandwidth_limit(self) -> pulumi.Output[_builtins.float]:
        """
        Daily bandwidth limit for the database
        """
        return pulumi.get(self, "db_daily_bandwidth_limit")

    @_builtins.property
    @pulumi.getter(name="dbDiskThreshold")
    def db_disk_threshold(self) -> pulumi.Output[_builtins.float]:
        """
        Disk threshold for the database
        """
        return pulumi.get(self, "db_disk_threshold")

    @_builtins.property
    @pulumi.getter(name="dbMaxClients")
    def db_max_clients(self) -> pulumi.Output[_builtins.float]:
        """
        Max clients for the database
        """
        return pulumi.get(self, "db_max_clients")

    @_builtins.property
    @pulumi.getter(name="dbMaxCommandsPerSecond")
    def db_max_commands_per_second(self) -> pulumi.Output[_builtins.float]:
        """
        Max commands per second for the database
        """
        return pulumi.get(self, "db_max_commands_per_second")

    @_builtins.property
    @pulumi.getter(name="dbMaxEntrySize")
    def db_max_entry_size(self) -> pulumi.Output[_builtins.float]:
        """
        Max entry size for the database
        """
        return pulumi.get(self, "db_max_entry_size")

    @_builtins.property
    @pulumi.getter(name="dbMaxRequestSize")
    def db_max_request_size(self) -> pulumi.Output[_builtins.float]:
        """
        Max request size for the database
        """
        return pulumi.get(self, "db_max_request_size")

    @_builtins.property
    @pulumi.getter(name="dbMemoryThreshold")
    def db_memory_threshold(self) -> pulumi.Output[_builtins.float]:
        """
        Memory threshold for the database
        """
        return pulumi.get(self, "db_memory_threshold")

    @_builtins.property
    @pulumi.getter
    def endpoint(self) -> pulumi.Output[_builtins.str]:
        """
        Database URL for connection
        """
        return pulumi.get(self, "endpoint")

    @_builtins.property
    @pulumi.getter
    def eviction(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Enable eviction, to evict keys when your database reaches the max size
        """
        return pulumi.get(self, "eviction")

    @_builtins.property
    @pulumi.getter(name="ipAllowlists")
    def ip_allowlists(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Ip CIDR allowlist for the database. If not set, all IPs are allowed to connect to the database.
        """
        return pulumi.get(self, "ip_allowlists")

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""Deprecated""")
    def multizone(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        When enabled, database becomes highly available and is deployed in multiple zones. (If changed to false from true, results in deletion and recreation of the resource)
        """
        return pulumi.get(self, "multizone")

    @_builtins.property
    @pulumi.getter
    def password(self) -> pulumi.Output[_builtins.str]:
        """
        Password of the database
        """
        return pulumi.get(self, "password")

    @_builtins.property
    @pulumi.getter
    def port(self) -> pulumi.Output[_builtins.float]:
        """
        Port of the endpoint
        """
        return pulumi.get(self, "port")

    @_builtins.property
    @pulumi.getter(name="primaryRegion")
    def primary_region(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Primary region for the database (Only works if region='global'. Can be one of [us-east-1, us-west-1, us-west-2, eu-central-1, eu-west-1, sa-east-1, ap-southeast-1, ap-southeast-2])
        """
        return pulumi.get(self, "primary_region")

    @_builtins.property
    @pulumi.getter(name="prodPack")
    def prod_pack(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether Prod Pack is enabled for the database.
        """
        return pulumi.get(self, "prod_pack")

    @_builtins.property
    @pulumi.getter(name="readOnlyRestToken")
    def read_only_rest_token(self) -> pulumi.Output[_builtins.str]:
        """
        Rest Token for the database.
        """
        return pulumi.get(self, "read_only_rest_token")

    @_builtins.property
    @pulumi.getter(name="readRegions")
    def read_regions(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Read regions for the database (Only works if region='global' and<span pulumi-lang-nodejs=" primaryRegion " pulumi-lang-dotnet=" PrimaryRegion " pulumi-lang-go=" primaryRegion " pulumi-lang-python=" primary_region " pulumi-lang-yaml=" primaryRegion " pulumi-lang-java=" primaryRegion " pulumi-lang-hcl=" primary_region "> primaryRegion </span>is set. Can be any combination of [us-east-1, us-west-1, us-west-2, eu-central-1, eu-west-1, sa-east-1, ap-southeast-1, ap-southeast-2], excluding the one given as primary.)
        """
        return pulumi.get(self, "read_regions")

    @_builtins.property
    @pulumi.getter(name="redisDatabaseId")
    def redis_database_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "redis_database_id")

    @_builtins.property
    @pulumi.getter
    def region(self) -> pulumi.Output[_builtins.str]:
        """
        Region of the database. For global gcp regions, use `gcp-global`. For globals, check for<span pulumi-lang-nodejs=" primaryRegion " pulumi-lang-dotnet=" PrimaryRegion " pulumi-lang-go=" primaryRegion " pulumi-lang-python=" primary_region " pulumi-lang-yaml=" primaryRegion " pulumi-lang-java=" primaryRegion " pulumi-lang-hcl=" primary_region "> primaryRegion </span>and<span pulumi-lang-nodejs=" readRegions " pulumi-lang-dotnet=" ReadRegions " pulumi-lang-go=" readRegions " pulumi-lang-python=" read_regions " pulumi-lang-yaml=" readRegions " pulumi-lang-java=" readRegions " pulumi-lang-hcl=" read_regions "> readRegions </span>fields
        """
        return pulumi.get(self, "region")

    @_builtins.property
    @pulumi.getter(name="restToken")
    def rest_token(self) -> pulumi.Output[_builtins.str]:
        """
        Rest Token for the database.
        """
        return pulumi.get(self, "rest_token")

    @_builtins.property
    @pulumi.getter
    def state(self) -> pulumi.Output[_builtins.str]:
        """
        State of the database
        """
        return pulumi.get(self, "state")

    @_builtins.property
    @pulumi.getter
    def tls(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        When enabled, data is encrypted in transit. TLS is enabled by default for newly created databases and cannot be disabled.
        """
        return pulumi.get(self, "tls")

    @_builtins.property
    @pulumi.getter(name="userEmail")
    def user_email(self) -> pulumi.Output[_builtins.str]:
        """
        User email for the database
        """
        return pulumi.get(self, "user_email")

